import crypto from 'node:crypto';
const COOKIE='cv_site_session',TTL=7*24*60*60*1000,stateStore=new Map();
function secret(){const s=process.env.CV_SESSION_SECRET||'';if(process.env.NODE_ENV==='production'&&!s)throw new Error('CV_SESSION_SECRET is required in production');return s||'development-only-change-me';}
function b64(v){return Buffer.from(v).toString('base64url')}
function ub64(v){return Buffer.from(v,'base64url').toString('utf8')}
function mac(v){return b64(crypto.createHmac('sha256',secret()).update(v).digest())}
function sign(payload){const body=b64(JSON.stringify(payload));return body+'.'+mac(body)}
function verify(value){try{const [body,sig]=String(value||'').split('.');if(!body||!sig)return null;const expected=mac(body);if(sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const data=JSON.parse(ub64(body));return data.exp>Date.now()?data:null}catch{return null}}
export function cookieHeader(value,maxAge=TTL){return value?COOKIE+'='+value+'; Path=/; HttpOnly; SameSite=Lax; Max-Age='+Math.floor(maxAge/1000):COOKIE+'=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0'}
export function createSession(email,role='user'){return sign({email:String(email).toLowerCase(),role:String(role),iat:Date.now(),exp:Date.now()+TTL})}
export function readSession(req){const raw=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='));return raw?verify(raw.slice(COOKIE.length+1)):null}
export function ownerEmails(){return [...new Set([process.env.CV_OWNER_EMAIL||'',...(String(process.env.CV_GOOGLE_OWNER_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()))].filter(Boolean))}
export function isOwnerEmail(email){return ownerEmails().includes(String(email||'').trim().toLowerCase())}
export function ownerConfigured(){return Boolean(process.env.CV_OWNER_EMAIL&&process.env.CV_OWNER_PASSWORD)||ownerEmails().length>0}
function h(value){return crypto.createHmac('sha256',secret()).update(String(value||'')).digest()}
export function verifyOwnerPassword(email,password){if(!process.env.CV_OWNER_EMAIL||!process.env.CV_OWNER_PASSWORD)return false;if(String(email||'').trim().toLowerCase()!==String(process.env.CV_OWNER_EMAIL).trim().toLowerCase())return false;const a=h(password),b=h(process.env.CV_OWNER_PASSWORD);return crypto.timingSafeEqual(a,b)}
export function googleConfigured(){return Boolean(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET&&process.env.GOOGLE_REDIRECT_URI)}
export function beginGoogleAuth({admin=false}={}){if(!googleConfigured())throw new Error('Google OAuth is not configured');const state=b64(crypto.randomBytes(24));stateStore.set(state,{admin:Boolean(admin),created:Date.now()});setTimeout(()=>stateStore.delete(state),10*60*1000);const u=new URL('https://accounts.google.com/o/oauth2/v2/auth');u.searchParams.set('client_id',process.env.GOOGLE_CLIENT_ID);u.searchParams.set('redirect_uri',process.env.GOOGLE_REDIRECT_URI);u.searchParams.set('response_type','code');u.searchParams.set('scope','openid email profile');u.searchParams.set('state',state);return u.toString()}
export async function completeGoogleAuth(code,state){const meta=stateStore.get(String(state||''));stateStore.delete(String(state||''));if(!meta||Date.now()-meta.created>10*60*1000)throw new Error('google_oauth_state_invalid');const token=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code:String(code||''),client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:process.env.GOOGLE_REDIRECT_URI,grant_type:'authorization_code'})}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error('google_token_exchange_failed:'+String(j.error_description||j.error||'unknown').slice(0,240));return j});
const user=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{authorization:'Bearer '+token.access_token}}).then(async r=>{const j=await r.json();if(!r.ok||!j.email_verified)throw new Error('google_email_not_verified');return j});
const email=String(user.email||'').toLowerCase(),owner=isOwnerEmail(email);if(meta.admin&&!owner)throw new Error('admin_owner_access_required');return {email,owner,admin:meta.admin}}
