import path from 'node:path';
import {inspectProjectArtifact,artifactFingerprint} from './artifact.js';
import {getProvider,listProviders} from './providers.js';
import {encryptSecret,decryptSecret} from '../security/vault.js';
import {compatibility} from './compatibility.js';
import {createDeploymentAttestation} from './attestation.js';
import {CODINGVIBES_VERSION} from '../version.js';

export function deploymentCatalog(){return listProviders()}
export function providerSecret(store,userId,provider){const row=store.getProviderConnection(userId,provider);if(!row&&provider==='hostinger')return providerSecret(store,userId,'github');if(!row)return null;let secret=decryptSecret(row.secret_ciphertext);try{const parsed=JSON.parse(secret);if(parsed&&typeof parsed==='object')return {...parsed,...row.metadata}}catch{}return {accessToken:secret,...row.metadata}}
export function connectProvider(store,userId,provider,{secret,metadata={}}={}){if(!secret)throw new Error('provider_secret_required');const encrypted=encryptSecret(secret);store.upsertProviderConnection(userId,provider,encrypted,metadata);return {provider,connected:true,metadata}}
export function disconnectProvider(store,userId,provider){store.deleteProviderConnection(userId,provider);return {provider,connected:false}}
export async function prepareDeploymentArtifact(project){if(!project?.repo_path)throw new Error('project_repository_not_initialized');const artifact=inspectProjectArtifact(project.repo_path);if(artifact.deploymentMetadata.missingFiles.length)throw Object.assign(new Error('project_invalid_missing_files:'+artifact.deploymentMetadata.missingFiles.join(', ')),{code:'INVALID_ARTIFACT',status:409});if(artifact.deploymentMetadata.secrets.length)throw Object.assign(new Error('project_contains_sensitive_files:'+artifact.deploymentMetadata.secrets.join(', ')),{code:'SENSITIVE_FILES',status:409});return {...artifact,fingerprint:artifactFingerprint(artifact)}}
export async function deployProject({store,userId,project,provider,options={}}={}){const p=getProvider(provider);if(!p)throw Object.assign(new Error('unsupported_deployment_provider'),{status:400});const artifact=await prepareDeploymentArtifact(project),compatibilityResult=compatibility(provider,artifact);if(!compatibilityResult.compatible)throw Object.assign(new Error(compatibilityResult.reason),{code:'DEPLOYMENT_INCOMPATIBLE',status:409});const credentials=provider==='manual'?null:providerSecret(store,userId,provider);if(provider!=='manual'&&!credentials)throw Object.assign(new Error('Connect '+p.label+' before deploying.'),{status:409,code:'PROVIDER_NOT_CONNECTED'});const deployment=store.createDeployment(userId,project.id,{provider,status:'queued',branch:options.branch||null,commitSha:options.commitSha||null,metadata:{artifactFingerprint:artifact.fingerprint,framework:artifact.framework,serverRequired:artifact.deploymentMetadata.serverRequired,attestation:createDeploymentAttestation({version:CODINGVIBES_VERSION,commitSha:options.commitSha||null,targetId:options.targetId||null,artifactFingerprint:artifact.fingerprint,verification:options.verification||{passed:false,reason:'verification_not_provided'}})}});try{store.updateDeployment(deployment.id,userId,{status:'deploying'});const result=await p.deploy({artifact,credentials,options});return {deployment:store.updateDeployment(deployment.id,userId,{status:result.status||'published',deployment_id:result.deploymentId||null,url:result.url||null,branch:result.branch||options.branch||null,commit_sha:result.commitSha||options.commitSha||null,metadata:{artifactFingerprint:artifact.fingerprint,framework:artifact.framework,providerProject:result.providerProject||null,file:result.file?.file||null,nextStep:result.nextStep||null,optimization:result.optimization||null,attestation:createDeploymentAttestation({version:CODINGVIBES_VERSION,commitSha:result.commitSha||options.commitSha||null,targetId:options.targetId||null,artifactFingerprint:artifact.fingerprint,verification:options.verification||{passed:false,reason:'verification_not_provided'}})}}),artifact}}catch(e){store.updateDeployment(deployment.id,userId,{status:'failed',error:String(e.message||e).slice(0,1000)});throw e}}
export async function exportProject({project}={}){const artifact=await prepareDeploymentArtifact(project),result=await getProvider('manual').deploy({artifact}),downloadName=path.basename(result.file?.file||result.deploymentId||'project.zip');return{artifact,deployment:{status:'ready',downloadPath:result.deploymentId,downloadName,optimization:result.optimization||null}}}

export function validateProvider(provider,artifact){return compatibility(provider,artifact)}
export async function authenticateProvider({store,userId,provider}={}){const p=getProvider(provider);if(!p)throw Object.assign(new Error('unsupported_deployment_provider'),{status:400});const credentials=providerSecret(store,userId,provider);if(!credentials)return{authenticated:false,provider};if(typeof p.authenticate==='function')return p.authenticate({credentials});return{authenticated:true,provider}}
export async function getDeploymentStatus({store,userId,deploymentId}={}){const d=store.getDeployment(deploymentId,userId);if(!d)throw Object.assign(new Error('deployment_not_found'),{status:404});const p=getProvider(d.provider);if(!p?.status)throw Object.assign(new Error('provider_status_not_supported'),{status:409});const credentials=d.provider==='manual'?null:providerSecret(store,d.user_id,d.provider);const result=await p.status({credentials,deploymentId:d.deployment_id,options:d.metadata||{}});return {...d, ...result}}
export function getDeploymentUrl(deployment){return deployment?.url||null}
export async function cancelDeployment({store,userId,deploymentId}={}){const d=store.getDeployment(deploymentId,userId);if(!d)throw Object.assign(new Error('deployment_not_found'),{status:404});const p=getProvider(d.provider);if(typeof p?.cancel!=='function')throw Object.assign(new Error('provider_cancel_not_supported'),{status:409});const credentials=d.provider==='manual'?null:providerSecret(store,d.user_id,d.provider);return p.cancel({credentials,deploymentId:d.deployment_id,options:d.metadata||{}})}
