import {spawn} from 'node:child_process';
import net from 'node:net';
import fs from 'node:fs';
import path from 'node:path';
function open(port,host='127.0.0.1'){return new Promise(resolve=>{const s=net.createConnection({port,host});s.once('connect',()=>{s.destroy();resolve(true)});s.once('error',()=>resolve(false));});}
async function freePort(start=4300){for(let p=start;p<start+100;p++)if(!await open(p))return p;throw new Error('No free preview port');}
async function waitFor(url){const deadline=Date.now()+20000;while(Date.now()<deadline){try{const r=await fetch(url);if(r.ok||r.status<500)return;}catch{}await new Promise(r=>setTimeout(r,200))}throw new Error('Container preview did not become ready');}
async function runDocker(args,{capture=true}={}){return new Promise((resolve,reject)=>{const p=spawn('docker',args,{stdio:capture?['ignore','pipe','pipe']:['ignore','ignore','pipe']});let out='',err='';if(p.stdout)p.stdout.on('data',d=>out+=d);if(p.stderr)p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('exit',code=>resolve({code:code??1,stdout:out,stderr:err}))});}
export async function startContainerPreview(workspace,{host='127.0.0.1',image=process.env.CODINGVIBES_CONTAINER_IMAGE||'node:22-bookworm-slim',dependencyApproved=false}={}){
 const port=await freePort();const logPath=path.join(workspace,'.codingvibes-preview-container.log');const network=dependencyApproved&&process.env.CODINGVIBES_DEPENDENCY_NETWORK?process.env.CODINGVIBES_DEPENDENCY_NETWORK:'none';const boot=dependencyApproved&&fs.existsSync(path.join(workspace,'package.json'))?'if [ -f package-lock.json ]; then npm ci --ignore-scripts; else npm install --ignore-scripts; fi; npm start':'npm start';const args=['run','-d','--rm','--init','--network',network,'--cpus','1','--memory','768m','--pids-limit','128','--cap-drop','ALL','--security-opt','no-new-privileges','--read-only','--tmpfs','/tmp:rw,nosuid,nodev','-p',`${host}:${port}:${port}`,'-v',`${path.resolve(workspace)}:/app:ro`,'-v',`${path.resolve(workspace)}/.codingvibes-node_modules:/app/node_modules:rw`,'-w','/app','-e','HOST=0.0.0.0',`-e`,`PORT=${port}`,image,'sh','-lc',boot];
 const started=await runDocker(args);if(started.code!==0)throw new Error(`Docker preview failed to start: ${started.stderr||started.stdout}`);const id=started.stdout.trim();fs.writeFileSync(logPath,started.stderr||'');const url=`http://${host}:${port}`;
 try{await waitFor(`${url}/api/health`);return{kind:'container',url,port,containerId:id,logPath,exec:async(command,args=[])=>{const r=await runDocker(['exec',id,command,...args]);return{ok:r.code===0,code:r.code,stdout:r.stdout,stderr:r.stderr};},stop:async()=>{await runDocker(['rm','-f',id]);}};}catch(e){await runDocker(['rm','-f',id]);throw new Error(`Container preview failed: ${e.message}`);}
}
