import fs from 'node:fs';
import path from 'node:path';

async function walk(dir,root=dir,out=[]){for(const name of fs.readdirSync(dir)){if(['.git','node_modules','.codingvibes'].includes(name))continue;const full=path.join(dir,name),rel=path.relative(root,full).replaceAll('\\','/'),st=fs.lstatSync(full);if(st.isSymbolicLink())continue;if(st.isDirectory())await walk(full,root,out);else out.push({source:full,destination:`/app/${rel}`});}return out;}

export class DaytonaRuntime{
 constructor({apiKey=process.env.DAYTONA_API_KEY||process.env.CODINGVIBES_DAYTONA_API_KEY,apiUrl=process.env.DAYTONA_API_URL,target=process.env.DAYTONA_TARGET}={}){this.config={apiKey,apiUrl,target};this.client=null;this.sandbox=null;this.port=process.env.CODINGVIBES_DAYTONA_PORT?Number(process.env.CODINGVIBES_DAYTONA_PORT):4300;}
 get enabled(){return Boolean(this.config.apiKey);}
 async sdk(){if(!this.enabled)throw new Error('Daytona runtime is not configured. Set DAYTONA_API_KEY.');if(this.client)return this.client;let mod;try{mod=await import('@daytona/sdk');}catch{throw new Error('Daytona runtime requires @daytona/sdk. Run npm install @daytona/sdk.');}const {Daytona}=mod;this.client=new Daytona(this.config);return this.client;}
 async start(workspace){const daytona=await this.sdk();this.sandbox=await daytona.create({language:'typescript',ephemeral:true,autoStopInterval:30,public:false});const files=await walk(workspace);if(files.length)await this.sandbox.fs.uploadFiles(files);const install=await this.sandbox.process.executeCommand('npm install --ignore-scripts --no-audit --no-fund','/app',undefined,180);if(install.exitCode!==0)throw new Error(`Daytona dependency install failed: ${install.result||''}`);await this.sandbox.process.executeCommand(`HOST=0.0.0.0 PORT=${this.port} nohup npm start >/tmp/codingvibes-preview.log 2>&1 &`,'/app',undefined,30);for(let i=0;i<60;i++){const r=await this.sandbox.process.executeCommand(`curl -fsS http://127.0.0.1:${this.port}/api/health >/dev/null`,'/app',undefined,10);if(r.exitCode===0)break;await new Promise(r=>setTimeout(r,250));if(i===59)throw new Error('Daytona preview did not become ready');}const preview=await this.sandbox.getSignedPreviewUrl(this.port,3600);return{kind:'daytona',url:preview.url,port:this.port,exec:async(command,args=[])=>{const safe=[command,...args].map(x=>JSON.stringify(String(x))).join(' ');const r=await this.sandbox.process.executeCommand(safe,'/app',undefined,180);return {ok:r.exitCode===0,code:r.exitCode??1,stdout:r.artifacts?.stdout||r.result||'',stderr:r.artifacts?.stderr||''};},stop:async()=>{try{await this.sandbox.process.executeCommand(`pkill -f 'npm start' || true`,'/app')}catch{}try{await this.sandbox.stop()}catch{}this.sandbox=null;}};}
}
