{id:'freelancer-business',label:'Freelancer Business',category:'Portfolio',kind:'portfolio',tier:'free',style:'minimal',experience:'motion',tags:['freelancer','portfolio','services'],prompt:'Create a freelancer website with service packages, selected work, testimonials, about, process, contact and inquiry form.',features:[]},

{id:'course-immersive',label:'Immersive Course Academy',category:'Education',kind:'education',tier:'pro',style:'futuristic',experience:'3d',tags:['courses','education','3d','learning'],prompt:'Create a modern learning platform landing site with an interactive 3D hero, course catalog, curriculum, instructors, outcomes, testimonials and enrollment CTA.',features:['advanced_animation']},
{id:'conference-immersive',label:'Conference 3D',category:'Event',kind:'event',tier:'pro',style:'futuristic',experience:'3d',tags:['conference','event','3d','speakers'],prompt:'Create an event website with a 3D venue hero, schedule, speakers, sponsors, maps, ticket tiers and animated transitions.',features:['advanced_animation']},
{id:'property-gallery',label:'Property Listing Gallery',category:'Real Estate',kind:'realEstate',tier:'free',style:'minimal',experience:'motion',tags:['real estate','listings','properties','agents'],prompt:'Create a data-driven property listing website with filters, cards, saved-search UI, property details, agents, inquiry forms and responsive mobile layout.',features:[]},
{id:'property-3d-developer',label:'Real Estate Developer 3D',category:'Real Estate',kind:'realEstate',tier:'pro',style:'futuristic',experience:'3d',featured:true,tags:['real estate developer','masterplan','3d','plots','units'],prompt:'Create a developer website with interactive 3D masterplan, buildings/plots, unit inventory, availability states, floorplan previews, amenity map and lead capture.',features:['advanced_animation']},

{id:'blog-magazine',label:'Editorial Magazine',category:'Content',kind:'content',tier:'free',style:'editorial',experience:'motion',tags:['blog','magazine','content','editorial'],prompt:'Create a magazine-style content site with featured stories, categories, search, article pages, author profiles, newsletter and accessible reading layout.',features:[]},
{id:'creator-store',label:'Creator Store + Portfolio',category:'Creator',kind:'ecommerce',tier:'free',style:'playful',experience:'motion',tags:['creator','digital products','portfolio','store'],prompt:'Create a creator website combining portfolio, digital products, bundles, testimonials, newsletter, about and a simple cart-ready storefront.',features:[]},
{id:'marketplace-3d',label:'Marketplace 3D',category:'Marketplace',kind:'marketplace',tier:'pro',style:'futuristic',experience:'3d',tags:['marketplace','vendors','3d','commerce'],prompt:'Create a marketplace experience with vendor profiles, categories, filters, product grid, 3D hero, product detail, cart and vendor storytelling.',features:['advanced_animation']},
{id:'saas-product-3d',label:'SaaS Product 3D',category:'SaaS',kind:'business',tier:'pro',style:'futuristic',experience:'3d',tags:['saas','3d','product','interactive'],prompt:'Create a SaaS product marketing site with an interactive 3D product/dashboard scene, feature hotspots, pricing, integrations, testimonials and conversion-focused motion.',features:['advanced_animation']}
];

function motionProfile(t){return t.experience==='3d'?{mode:'cinematic',scroll:'camera-story',reveal:'depth',hover:'focus',transition:'shared-camera'}:{mode:'smooth',scroll:'story',reveal:'clip-and-fade',hover:'magnetic',transition:'shared-layout'};}
function publicTemplate(t){return {...t,motion:motionProfile(t),features:[...t.features],prompt:undefined,tags:[...t.tags]};}

export function listTemplates(){return TEMPLATES.map(publicTemplate);}
export function getTemplate(id){const t=TEMPLATES.find(t=>t.id===String(id));return t?publicTemplate(t):null;}
export function searchTemplates(query='',{category='',kind='',experience='',tier='',featured=false,limit=80}={}){