const TEMPLATES = [
{id:'aurora-saas',label:'Aurora SaaS',category:'SaaS',tier:'free',style:'futuristic',tags:['saas','ai','b2b'],prompt:'Create a polished SaaS landing site with pricing, product benefits, testimonials, FAQ, signup CTA and responsive sections.',features:[]},
{id:'studio-agency',label:'Studio Agency',category:'Agency',tier:'free',style:'editorial',tags:['agency','portfolio','case studies'],prompt:'Create a premium creative agency site with case studies, services, process, team and contact CTA.',features:[]},
{id:'creator-portfolio',label:'Creator Portfolio',category:'Portfolio',tier:'free',style:'minimal',tags:['portfolio','personal','creative'],prompt:'Create a striking personal portfolio with project grid, about, experience, testimonials and contact.',features:[]},
{id:'fashion-commerce',label:'Fashion Commerce',category:'Commerce',tier:'free',style:'luxury',tags:['fashion','shop','commerce'],prompt:'Create a luxury fashion ecommerce storefront with product grid, product detail, cart-ready checkout UI, editorial sections and responsive design.',features:[]},
{id:'restaurant',label:'Restaurant & Dining',category:'Business',tier:'free',style:'editorial',tags:['restaurant','menu','booking'],prompt:'Create an elegant restaurant website with menu, reservations, location, gallery, chef story and mobile-friendly navigation.',features:[]},
{id:'hotel-resort',label:'Hotel & Resort',category:'Hospitality',tier:'free',style:'luxury',tags:['hotel','resort','booking'],prompt:'Create a premium hotel/resort website with rooms, amenities, gallery, experiences, location and booking CTA.',features:[]},
{id:'real-estate-classic',label:'Real Estate Classic',category:'Real Estate',tier:'free',style:'modern',tags:['real estate','property','listings'],prompt:'Create a professional real estate website with property search, listing cards, detail pages, agent profiles and lead forms.',features:[]},
{id:'real-estate-3d-tour',label:'Real Estate 3D Tour',category:'Real Estate',tier:'pro',style:'luxury',tags:['real estate','3d','virtual tour','house','property'],prompt:'Create an immersive real estate property showcase with an interactive Three.js 3D house scene, orbit controls, room hotspots, floor-plan overlay, cinematic camera path, property details, gallery, CTA and an embedded video walkthrough. Support a user-supplied GLB/GLTF model when available and provide a procedural house fallback when it is not. Include a video section that can play an MP4/WebM tour and a lightweight browser recording control for the camera tour.',features:['advanced_animation']},
{id:'property-development',label:'Property Development 3D',category:'Real Estate',tier:'pro',style:'futuristic',tags:['development','3d masterplan','map','real estate'],prompt:'Create an interactive property-development landing site with a 3D masterplan, clickable plot markers, project phases, unit detail drawer, amenities and animated camera transitions.',features:['advanced_animation']},
{id:'architecture-immersive',label:'Architecture Immersive',category:'3D',tier:'pro',style:'editorial',tags:['architecture','3d','portfolio'],prompt:'Create an architecture studio website with a cinematic 3D scene, camera choreography, material cards, project storytelling, scroll-driven transitions and reduced-motion fallback.',features:['advanced_animation']},
{id:'product-3d-launch',label:'3D Product Launch',category:'3D',tier:'pro',style:'minimal',tags:['product','3d','launch'],prompt:'Create a product launch website with an interactive 3D product viewer, explode/rotate interactions, feature callouts, specification tabs, animated storytelling and conversion CTA.',features:['advanced_animation']},
{id:'automotive-showcase',label:'Automotive Showcase',category:'3D',tier:'pro',style:'futuristic',tags:['car','automotive','3d'],prompt:'Create a cinematic automotive website with an interactive 3D vehicle, orbit camera, paint/material switcher, spec cards, scroll storytelling and optional driving video.',features:['advanced_animation']},
{id:'jewelry-atelier',label:'Jewelry Atelier',category:'Commerce',tier:'pro',style:'luxury',tags:['jewelry','luxury','3d'],prompt:'Create a luxury jewelry site with a 3D hero object, product storytelling, zoom/rotate interaction, collection pages, editorial imagery and elegant motion.',features:['advanced_animation']},
{id:'tech-event',label:'Tech Event',category:'Event',tier:'free',style:'bold',tags:['event','conference','schedule'],prompt:'Create a high-energy tech conference site with speakers, schedule, venue, sponsors, registration CTA and responsive layout.',features:[]},
{id:'course-academy',label:'Course Academy',category:'Education',tier:'free',style:'modern',tags:['education','courses','learning'],prompt:'Create an online learning landing site with course catalog, instructor profiles, outcomes, curriculum and enrollment CTA.',features:[]},
{id:'mobile-app',label:'Mobile App Launch',category:'Product',tier:'free',style:'playful',tags:['app','mobile','saas'],prompt:'Create a mobile app launch page with app screenshots, feature storytelling, social proof, pricing and download CTA.',features:[]},
{id:'fintech',label:'Fintech Product',category:'Finance',tier:'free',style:'minimal',tags:['fintech','finance','dashboard'],prompt:'Create a trustworthy fintech marketing site with product overview, security messaging, pricing, feature comparisons and signup CTA.',features:[]},
{id:'cybersecurity',label:'Cybersecurity',category:'Technology',tier:'free',style:'futuristic',tags:['security','b2b','technology'],prompt:'Create a cybersecurity company site with threat-focused hero, capabilities, integrations, case studies, trust signals and contact CTA.',features:[]},
{id:'nonprofit',label:'Nonprofit Impact',category:'Nonprofit',tier:'free',style:'editorial',tags:['charity','nonprofit','donations'],prompt:'Create an accessible nonprofit website with mission, impact stories, programs, events and donation CTA.',features:[]},
{id:'photography',label:'Photography',category:'Creative',tier:'free',style:'minimal',tags:['photography','gallery','portfolio'],prompt:'Create a photographer portfolio with editorial gallery, project stories, about, services and inquiry flow.',features:[]},
{id:'music-artist',label:'Music Artist',category:'Creative',tier:'free',style:'bold',tags:['music','artist','tour'],prompt:'Create a modern musician website with music embeds, releases, tour dates, videos, merch CTA and mailing list.',features:[]},
{id:'saas-analytics',label:'SaaS Analytics',category:'SaaS',tier:'free',style:'modern',tags:['analytics','dashboard','b2b'],prompt:'Create a SaaS analytics marketing site with dashboard preview, metrics storytelling, integrations, pricing and signup CTA.',features:[]},
{id:'ai-lab',label:'AI Research Lab',category:'Technology',tier:'pro',style:'futuristic',tags:['ai','research','interactive'],prompt:'Create an experimental AI lab website with interactive motion, visualized research topics, model cards, papers, demos and cinematic transitions.',features:['advanced_animation']},
{id:'immersive-story',label:'Immersive Story',category:'3D',tier:'pro',style:'editorial',tags:['storytelling','parallax','3d'],prompt:'Create an immersive editorial story site using scroll-driven camera movement, depth layers, parallax, animated typography and progressive enhancement.',features:['advanced_animation']},
{id:'video-portfolio',label:'Cinematic Video Portfolio',category:'Creative',tier:'pro',style:'luxury',tags:['video','portfolio','motion'],prompt:'Create a cinematic video portfolio with fullscreen media, reel playback, project case studies, smooth transitions and accessible video controls.',features:['advanced_animation']},
{id:'game-studio',label:'Game Studio',category:'Entertainment',tier:'pro',style:'futuristic',tags:['game','3d','studio'],prompt:'Create a game studio marketing site with interactive 3D hero, game cards, trailers, lore, team and release CTA.',features:['advanced_animation']},
{id:'real-estate-video-tour',label:'Property + AI Video Tour',category:'Real Estate',tier:'pro',style:'luxury',tags:['real estate','video','3d','ai video'],prompt:'Create a luxury property site combining an interactive 3D home tour, cinematic camera path, floor plan, room hotspots, photo gallery and an AI-video-tour area with clear loading/error states.',features:['advanced_animation','ai_video']},
];

export function listTemplates(){return TEMPLATES.map(t=>({...t,features:[...t.features],prompt:undefined}));}
export function getTemplate(id){return TEMPLATES.find(t=>t.id===String(id))||null;}
export function searchTemplates(query='',{category='',limit=60}={}){
 const q=String(query).toLowerCase().trim();const c=String(category).toLowerCase().trim();
 return listTemplates().filter(t=>(!c||t.category.toLowerCase()===c||t.tags.some(x=>x.toLowerCase()===c))&&(!q||[t.label,t.category,...t.tags,t.style].join(' ').toLowerCase().includes(q))).slice(0,limit);
}
export function templatePrompt(id){
 const t=getTemplate(id);return t? t.prompt : '';
}
