import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawn} from 'node:child_process';

const PORT=Number(process.env.PORT||8788);
const TOKEN=process.env.CODINGVIBES_LINUX_RUNNER_TOKEN||'';
if(!TOKEN)throw new Error('CODINGVIBES_LINUX_RUNNER_TOKEN is required');
const ROOT=process.env.CODINGVIBES_LINUX_WORK_ROOT||path.join(os.tmpdir(),'codingvibes-linux-runs');
const MAX=Number(process.env.CODINGVIBES_LINUX_MAX_BYTES||100*1024*1024);
const MAX_FILES=Number(process.env.CODINGVIBES_LINUX_MAX_FILES||6000);
const TIMEOUT=Number(process.env.CODINGVIBES_LINUX_JOB_TIMEOUT_MS||20*60_000);
const ARTIFACT_MAX=Number(process.env.CODINGVIBES_ARTIFACT_MAX_BYTES||500*1024*1024);
const UPLOAD_URL=process.env.CODINGVIBES_ARTIFACT_UPLOAD_URL||'';
const UPLOAD_TOKEN=process.env.CODINGVIBES_ARTIFACT_UPLOAD_TOKEN||'';
const IMAGES={android:process.env.CODINGVIBES_ANDROID_RUNNER_IMAGE||'ghcr.io/codingvibes/runner-android:2.6.0',flutter:process.env.CODINGVIBES_FLUTTER_RUNNER_IMAGE||'ghcr.io/codingvibes/runner-flutter:2.6.0',rust:process.env.CODINGVIBES_RUST_RUNNER_IMAGE||'ghcr.io/codingvibes/runner-rust:2.6.0'};
const DEP_NETWORK=process.env.CODINGVIBES_DEPENDENCY_NETWORK||'';
const CONCURRENCY=Number(process.env.CODINGVIBES_LINUX_MAX_CONCURRENCY||1);
let active=0;
fs.mkdirSync(ROOT,{recursive:true,mode:0o700});
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function json(res,status,payload){res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(payload));}
function read(req){return new Promise((resolve,reject)=>{let n=0,parts=[];req.on('data',d=>{n+=d.length;if(n>MAX){req.destroy();reject(new Error('payload too large'));return}parts.push(d)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(parts).toString('utf8')))}catch(e){reject(e)}});req.on('error',reject)})}
function safe(rel){const p=path.posix.normalize(String(rel||''));return p&&!p.startsWith('../')&&!p.includes('/../')&&!path.isAbsolute(p)&&!p.includes('\0')&&p!=='.'?p:null;}
function manifestDigest(files){const h=crypto.createHash('sha256');for(const f of [...files].sort((a,b)=>a.path.localeCompare(b.path)))h.update(f.path).update('\0').update(f.sha256).update('\0');return h.digest('hex');}
function writeFiles(root,files){if(!Array.isArray(files)||files.length>MAX_FILES)throw new Error('invalid file set');let total=0;for(const f of files){const rel=safe(f.path);if(!rel||/^(\.env(?:\..*)?|.*\.(pem|key|p12|pfx|jks|keystore))$/i.test(path.posix.basename(rel))&&path.posix.basename(rel)!=='.env.example')throw new Error(`secret file rejected: ${rel}`);if(typeof f.content!=='string'||!/^[a-f0-9]{64}$/i.test(String(f.sha256||'')))throw new Error('invalid manifest entry');const data=Buffer.from(f.content,'base64');if(data.length>10*1024*1024)throw new Error(`file too large: ${rel}`);total+=data.length;if(total>MAX)throw new Error('workspace exceeds byte limit');const dest=path.join(root,rel);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,data,{mode:0o600});}}
function allowedTarget(id){return ['android-kotlin','android-twa','mobile-flutter','desktop-tauri'].includes(id);}
function imageFor(target){if(['android-kotlin','android-twa'].includes(target))return IMAGES.android;if(target==='mobile-flutter')return IMAGES.flutter;return IMAGES.rust;}
function commandFor(root,target,phase){if(['android-kotlin','android-twa'].includes(target)){const gradle=fs.existsSync(path.join(root,'gradlew'))?'./gradlew':'gradle';return phase==='dependencies'?[gradle,['dependencies']]:[gradle,['test','assembleDebug']];}if(target==='mobile-flutter')return phase==='dependencies'?['flutter',['pub','get']]:['bash',['-lc','flutter analyze && flutter test && flutter build apk --debug']];if(target==='desktop-tauri')return phase==='dependencies'?['cargo',['fetch']]:['bash',['-lc','cargo check && cargo test --no-run && cargo tauri build']];throw new Error('unsupported target');}
function runDocker(root,target,phase){return new Promise(resolve=>{const image=imageFor(target);const network=phase==='dependencies'?DEP_NETWORK:'none';if(phase==='dependencies'&&!/^codingvibes-deps-[a-z0-9-]{1,48}$/.test(network))return resolve({ok:false,code:78,stdout:'',stderr:'controlled dependency network is not configured'});const prod=process.env.NODE_ENV==='production';if(prod&&!/@sha256:[a-f0-9]{64}$/i.test(image))return resolve({ok:false,code:78,stdout:'',stderr:'production runner images must be digest pinned'});let args=['run','--rm','--init','--network',network,'--cpus','2','--memory','4g','--pids-limit','512','--cap-drop','ALL','--security-opt','no-new-privileges','--security-opt','seccomp=default','--read-only','--tmpfs','/tmp:rw,nosuid,nodev','-v',`${root}:/workspace:rw`,'-w','/workspace'];const targetCmd=commandFor(root,target,phase);args.push(image,targetCmd[0],...targetCmd[1]);const env={CI:'1',HOME:'/workspace/.home',PATH:process.env.PATH||'/usr/local/bin:/usr/bin:/bin'};const p=spawn('docker',args,{stdio:['ignore','pipe','pipe'],shell:false,env});let stdout='',stderr='',timed=false;p.stdout.on('data',d=>stdout=(stdout+d).slice(-120000));p.stderr.on('data',d=>stderr=(stderr+d).slice(-120000));const t=setTimeout(()=>{timed=true;p.kill('SIGTERM');setTimeout(()=>p.kill('SIGKILL'),2000).unref()},TIMEOUT);p.on('close',(code)=>{clearTimeout(t);resolve({ok:code===0&&!timed,code:code??1,stdout,stderr,timedOut:timed})});p.on('error',e=>{clearTimeout(t);resolve({ok:false,code:127,stdout,stderr:e.message,timedOut:false})})})}
function collect(root){const out=[],exts=new Set(['.apk','.aab','.dmg','.msi','.exe','.deb','.rpm']);const walk=dir=>{for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(['.git','node_modules','.codingvibes'].includes(entry.name))continue;const full=path.join(dir,entry.name);if(entry.isDirectory())walk(full);else if(entry.isFile()&&exts.has(path.extname(entry.name).toLowerCase())){const b=fs.readFileSync(full);if(b.length<=ARTIFACT_MAX)out.push({path:full,size:b.length,sha256:sha(b),type:path.extname(full).slice(1)})}}};walk(root);return out;}
async function upload(file){if(!UPLOAD_URL)return {uploaded:false,reason:'artifact upload URL not configured'};const body=fs.readFileSync(file.path);const parsed=new URL(UPLOAD_URL);if(process.env.NODE_ENV==='production'&&parsed.protocol!=='https:')return {uploaded:false,reason:'production uploads require HTTPS'};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),60_000);try{const headers={'content-type':'application/octet-stream','content-length':String(body.length),'x-artifact-sha256':file.sha256};if(UPLOAD_TOKEN)headers.authorization=`Bearer ${UPLOAD_TOKEN}`;const res=await fetch(UPLOAD_URL,{method:'PUT',headers,body,signal:controller.signal});const echoed=res.headers.get('x-artifact-sha256')||res.headers.get('x-uploaded-sha256');return {uploaded:res.ok&&(!echoed||echoed===file.sha256),acknowledged:Boolean(echoed),url:res.url,status:res.status,sha256:file.sha256};}catch(e){return {uploaded:false,reason:e.name==='AbortError'?'artifact upload timeout':e.message,sha256:file.sha256};}finally{clearTimeout(timer);}}
const server=http.createServer(async(req,res)=>{if(req.method==='GET'&&req.url==='/health')return json(res,200,{ok:true,runner:'linux-docker',active,capacity:CONCURRENCY,targets:Object.keys(IMAGES),artifactUploadConfigured:Boolean(UPLOAD_URL)});if(req.method!=='POST'||req.url!=='/build')return json(res,404,{error:'not found'});if(req.headers.authorization!==`Bearer ${TOKEN}`)return json(res,401,{error:'unauthorized'});if(active>=CONCURRENCY)return json(res,429,{error:'runner busy'});active++;let work=null;try{const body=await read(req);if(body.schema!=='codingvibes.linux-job.v1')throw new Error('unsupported job schema');if(!allowedTarget(body.target))throw new Error('unsupported target');if(!body.jobId)throw new Error('jobId required');const digest=manifestDigest(body.files||[]);if(digest!==body.workspaceManifest)throw new Error('workspace manifest mismatch');work=path.join(ROOT,crypto.randomUUID());fs.mkdirSync(work,{recursive:true,mode:0o700});writeFiles(work,body.files||[]);const dep=await runDocker(work,body.target,'dependencies');const build=dep.ok?await runDocker(work,body.target,'build'):dep;const artifacts=build.ok?collect(work):[];const uploads=[];for(const artifact of artifacts)uploads.push({...artifact,upload:await upload(artifact)});const ok=build.ok&&artifacts.length>0&&uploads.length===artifacts.length&&uploads.every(x=>x.upload.uploaded&&(process.env.NODE_ENV!=='production'||x.upload.acknowledged));const safeArtifacts=artifacts.map((a)=>({path:path.relative(work,a.path),size:a.size,sha256:a.sha256,type:a.type}));const safeUploads=uploads.map(x=>({path:path.relative(work,x.path),size:x.size,sha256:x.sha256,type:x.type,upload:x.upload}));const result={ok,status:ok?'verified':build.ok?'artifact-upload-failed':'failed',jobId:body.jobId,workspaceManifest:digest,results:[{dependency:dep,build}],artifacts:safeArtifacts,uploads:safeUploads};fs.rmSync(work,{recursive:true,force:true});work=null;return json(res,ok?200:422,result);}catch(e){if(work)try{fs.rmSync(work,{recursive:true,force:true})}catch{}return json(res,400,{ok:false,error:e.message});}finally{active--;}});
server.listen(PORT,()=>console.log(`codingVibes Linux runner listening on :${PORT}`));
