import fs from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';

export class Store{
  constructor(filename=process.env.DATABASE_PATH||'./data/codingvibes.db'){
    fs.mkdirSync(path.dirname(path.resolve(filename)),{recursive:true});
    this.db=new DatabaseSync(filename);
    this.db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');
    this.migrate();
  }
  now(){return new Date().toISOString();}
  migrate(){
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS auth_sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,repo_path TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id TEXT NOT NULL,title TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY,session_id TEXT NOT NULL,user_id TEXT NOT NULL,status TEXT NOT NULL,request TEXT NOT NULL,target_id TEXT,spec_json TEXT,workspace TEXT,preview_url TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(session_id) REFERENCES sessions(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS changesets(id TEXT PRIMARY KEY,run_id TEXT NOT NULL,status TEXT NOT NULL,summary TEXT,operations_json TEXT,commit_sha TEXT,created_at TEXT NOT NULL,FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS tool_calls(id TEXT PRIMARY KEY,run_id TEXT,tool TEXT NOT NULL,permission TEXT NOT NULL,input_json TEXT,before_json TEXT,after_json TEXT,result_json TEXT,created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS evidence(id TEXT PRIMARY KEY,run_id TEXT NOT NULL,type TEXT NOT NULL,payload_json TEXT,created_at TEXT NOT NULL,FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,session_id TEXT NOT NULL,role TEXT NOT NULL,content TEXT NOT NULL,metadata_json TEXT,created_at TEXT NOT NULL,FOREIGN KEY(session_id) REFERENCES sessions(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS run_events(id TEXT PRIMARY KEY,run_id TEXT NOT NULL,type TEXT NOT NULL,payload_json TEXT,created_at TEXT NOT NULL,FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS runner_nodes(id TEXT PRIMARY KEY,name TEXT NOT NULL,capability TEXT NOT NULL,labels_json TEXT,metadata_json TEXT,status TEXT NOT NULL,last_heartbeat TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS artifacts(id TEXT PRIMARY KEY,run_id TEXT NOT NULL,type TEXT NOT NULL,path TEXT NOT NULL,size INTEGER NOT NULL,sha256 TEXT NOT NULL,stored_path TEXT,url TEXT,created_at TEXT NOT NULL,FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS agent_tasks(id TEXT PRIMARY KEY,run_id TEXT NOT NULL,key TEXT NOT NULL,title TEXT NOT NULL,phase TEXT NOT NULL,status TEXT NOT NULL,dependencies_json TEXT,metadata_json TEXT,started_at TEXT,finished_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(run_id,key),FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS usage_events(id TEXT PRIMARY KEY,run_id TEXT,user_id TEXT NOT NULL,provider TEXT,model TEXT,tier TEXT,input_tokens INTEGER DEFAULT 0,output_tokens INTEGER DEFAULT 0,tool_calls INTEGER DEFAULT 0,duration_ms INTEGER DEFAULT 0,created_at TEXT NOT NULL,FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS repository_indexes(run_id TEXT PRIMARY KEY,index_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS run_checkpoints(id TEXT PRIMARY KEY,run_id TEXT NOT NULL,name TEXT NOT NULL,path TEXT NOT NULL,metadata_json TEXT,created_at TEXT NOT NULL,FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS run_goals(id TEXT PRIMARY KEY,run_id TEXT UNIQUE NOT NULL,objective TEXT NOT NULL,completion_criteria_json TEXT,constraints_json TEXT,status TEXT NOT NULL,metadata_json TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS billing_accounts(user_id TEXT PRIMARY KEY,plan TEXT NOT NULL DEFAULT 'free',status TEXT NOT NULL DEFAULT 'active',stripe_customer_id TEXT,stripe_subscription_id TEXT,current_period_end TEXT,cancel_at_period_end INTEGER DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS dependency_requests(id TEXT PRIMARY KEY,run_id TEXT NOT NULL,dependencies_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',approved_at TEXT,approved_by TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS media_jobs(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,status TEXT NOT NULL,prompt TEXT NOT NULL,model TEXT NOT NULL,ratio TEXT NOT NULL,duration INTEGER NOT NULL,runway_task_id TEXT,source_url TEXT,stored_path TEXT,size INTEGER DEFAULT 0,error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS project_content(project_id TEXT PRIMARY KEY,user_id TEXT NOT NULL,content_json TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS provider_connections(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,provider TEXT NOT NULL,secret_ciphertext TEXT NOT NULL,metadata_json TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(user_id,provider),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS deployments(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,project_id TEXT NOT NULL,provider TEXT NOT NULL,status TEXT NOT NULL,deployment_id TEXT,url TEXT,branch TEXT,commit_sha TEXT,error TEXT,metadata_json TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS oauth_states(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,provider TEXT NOT NULL,state TEXT NOT NULL,expires_at TEXT NOT NULL,metadata_json TEXT,created_at TEXT NOT NULL,UNIQUE(provider,state),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS project_assets(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id TEXT NOT NULL,name TEXT NOT NULL,mime TEXT NOT NULL,kind TEXT NOT NULL,role TEXT NOT NULL,size INTEGER NOT NULL,sha256 TEXT NOT NULL,public_path TEXT NOT NULL,metadata_json TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS visual_baselines(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,user_id TEXT NOT NULL,route TEXT NOT NULL,stored_path TEXT NOT NULL,size INTEGER NOT NULL,sha256 TEXT NOT NULL,width INTEGER,height INTEGER,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(project_id,route),FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id); CREATE INDEX IF NOT EXISTS idx_provider_connections_user ON provider_connections(user_id,provider); CREATE INDEX IF NOT EXISTS idx_deployments_project ON deployments(project_id,created_at); CREATE INDEX IF NOT EXISTS idx_oauth_states_state ON oauth_states(provider,state,expires_at); CREATE INDEX IF NOT EXISTS idx_sessions_project ON sessions(project_id); CREATE INDEX IF NOT EXISTS idx_run_goals_run ON run_goals(run_id);
      CREATE INDEX IF NOT EXISTS idx_runs_session ON runs(session_id); CREATE INDEX IF NOT EXISTS idx_project_content_user ON project_content(user_id); CREATE INDEX IF NOT EXISTS idx_project_assets_project ON project_assets(project_id,created_at); CREATE INDEX IF NOT EXISTS idx_visual_baselines_project ON visual_baselines(project_id,route); CREATE INDEX IF NOT EXISTS idx_agent_tasks_run ON agent_tasks(run_id,status); CREATE INDEX IF NOT EXISTS idx_evidence_run ON evidence(run_id); CREATE INDEX IF NOT EXISTS idx_events_run ON run_events(run_id); CREATE INDEX IF NOT EXISTS idx_runner_nodes_capability ON runner_nodes(capability); CREATE INDEX IF NOT EXISTS idx_artifacts_run ON artifacts(run_id);
    `);
    const projectCols=this.db.prepare('PRAGMA table_info(projects)').all().map(x=>x.name);
    if(!projectCols.includes('repo_path'))this.db.exec('ALTER TABLE projects ADD COLUMN repo_path TEXT');
    const runCols=this.db.prepare('PRAGMA table_info(runs)').all().map(x=>x.name);
    if(!runCols.includes('target_id'))this.db.exec('ALTER TABLE runs ADD COLUMN target_id TEXT');
    const billingCols=this.db.prepare('PRAGMA table_info(billing_accounts)').all().map(x=>x.name);
    if(!billingCols.includes('video_trial_used'))this.db.exec('ALTER TABLE billing_accounts ADD COLUMN video_trial_used INTEGER DEFAULT 0');
    const usageCols=this.db.prepare('PRAGMA table_info(usage_events)').all().map(x=>x.name);
    if(!usageCols.includes('estimated_cost_usd'))this.db.exec('ALTER TABLE usage_events ADD COLUMN estimated_cost_usd REAL');
  }
  createUser(email,passwordHash){const id=randomUUID(),now=this.now();this.db.prepare('INSERT INTO users VALUES (?,?,?,?)').run(id,String(email).toLowerCase(),passwordHash,now);this.db.prepare('INSERT INTO billing_accounts(user_id,plan,status,created_at,updated_at) VALUES (?,?,?,?,?)').run(id,'free','active',now,now);return this.getUser(id);}
  getUser(id){return this.db.prepare('SELECT id,email,created_at FROM users WHERE id=?').get(id)||null;}
  getUserByEmail(email){return this.db.prepare('SELECT * FROM users WHERE lower(email)=lower(?)').get(email)||null;}
  getBilling(userId){const x=this.db.prepare('SELECT * FROM billing_accounts WHERE user_id=?').get(userId);if(x)return x;const now=this.now();this.db.prepare('INSERT INTO billing_accounts(user_id,plan,status,created_at,updated_at) VALUES (?,?,?,?,?)').run(userId,'free','active',now,now);return this.db.prepare('SELECT * FROM billing_accounts WHERE user_id=?').get(userId);}
  updateBilling(userId,patch={}){const current=this.getBilling(userId),fields=[],vals=[];for(const k of ['plan','status','stripe_customer_id','stripe_subscription_id','current_period_end','cancel_at_period_end'])if(k in patch){fields.push(`${k}=?`);vals.push(patch[k]);}if(!fields.length)return current;fields.push('updated_at=?');vals.push(this.now(),userId);this.db.prepare(`UPDATE billing_accounts SET ${fields.join(',')} WHERE user_id=?`).run(...vals);return this.getBilling(userId);}
  getBillingBySubscription(subscriptionId){return this.db.prepare('SELECT * FROM billing_accounts WHERE stripe_subscription_id=?').get(subscriptionId)||null;}
  consumeVideoTrial(userId){const r=this.db.prepare("UPDATE billing_accounts SET video_trial_used=1,updated_at=? WHERE user_id=? AND plan='free' AND COALESCE(video_trial_used,0)=0").run(this.now(),userId);return Number(r.changes||0)>0;}
  monthlyVideoSeconds(userId,period){const key=String(period);const row=this.db.prepare("SELECT COALESCE(SUM(duration),0) seconds FROM media_jobs WHERE user_id=? AND substr(created_at,1,7)=? AND status IN ('queued','running','succeeded')").get(userId,key);return Number(row?.seconds||0);}
  createMediaJob(userId,{status='queued',prompt,model,ratio,duration,runwayTaskId=null,sourceUrl=null,storedPath=null,size=0,error=null}={}){const id=randomUUID(),now=this.now();this.db.prepare('INSERT INTO media_jobs(id,user_id,status,prompt,model,ratio,duration,runway_task_id,source_url,stored_path,size,error,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,userId,status,String(prompt),String(model),String(ratio),Number(duration),runwayTaskId,sourceUrl,storedPath,Number(size||0),error,now,now);return this.getMediaJob(id,userId);}
  getMediaJob(id,userId){return this.db.prepare('SELECT * FROM media_jobs WHERE id=? AND user_id=?').get(id,userId)||null;}
  updateMediaJob(id,userId,patch={}){const current=this.getMediaJob(id,userId);if(!current)throw new Error('Media job not found');const allowed=['status','runway_task_id','source_url','stored_path','size','error'];const fields=[],vals=[];for(const k of allowed)if(k in patch){fields.push(`${k}=?`);vals.push(patch[k]);}if(!fields.length)return current;fields.push('updated_at=?');vals.push(this.now(),id,userId);this.db.prepare(`UPDATE media_jobs SET ${fields.join(',')} WHERE id=? AND user_id=?`).run(...vals);return this.getMediaJob(id,userId);}
  monthlyUsage(userId,period){const key=String(period);const rows=this.db.prepare("SELECT COUNT(*) runs FROM runs WHERE user_id=? AND substr(created_at,1,7)=?").get(userId,key);const tokens=this.db.prepare("SELECT COALESCE(SUM(input_tokens+output_tokens),0) tokens FROM usage_events WHERE user_id=? AND substr(created_at,1,7)=?").get(userId,key);return {period:key,runs:Number(rows?.runs||0),tokens:Number(tokens?.tokens||0)};}
  createAuthSession(userId,days=7){const id=randomUUID(),now=this.now(),expires=new Date(Date.now()+days*864e5).toISOString();this.db.prepare('INSERT INTO auth_sessions VALUES (?,?,?,?)').run(id,userId,expires,now);return {id,expiresAt:expires};}
  getAuthSession(id){return this.db.prepare('SELECT a.*,u.email FROM auth_sessions a JOIN users u ON u.id=a.user_id WHERE a.id=? AND a.expires_at>?').get(id,this.now())||null;}
  deleteAuthSession(id){this.db.prepare('DELETE FROM auth_sessions WHERE id=?').run(id);}
  createProject(userId,{name}){const id=randomUUID(),now=this.now(),slug=`${String(name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)||'project'}-${id.slice(0,8)}`;this.db.prepare('INSERT INTO projects(id,user_id,name,slug,repo_path,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(id,userId,String(name),slug,null,now,now);return this.getProject(id,userId);}
  getProject(id,userId){return this.db.prepare('SELECT * FROM projects WHERE id=? AND user_id=?').get(id,userId)||null;}
  listProjects(userId){return this.db.prepare('SELECT id,name,slug,repo_path,created_at,updated_at FROM projects WHERE user_id=? ORDER BY updated_at DESC').all(userId).map(p=>({...p,repo_path:undefined}));}
  updateProjectRepo(id,repoPath){this.db.prepare('UPDATE projects SET repo_path=?,updated_at=? WHERE id=?').run(repoPath,this.now(),id);return this.db.prepare('SELECT * FROM projects WHERE id=?').get(id)||null;}
  deleteProject(id,userId){this.db.prepare('DELETE FROM projects WHERE id=? AND user_id=?').run(id,userId);return true;}
  upsertProviderConnection(userId,provider,secretCiphertext,metadata={}){const now=this.now(),id=randomUUID(),existing=this.db.prepare('SELECT id FROM provider_connections WHERE user_id=? AND provider=?').get(userId,provider);if(existing)this.db.prepare('UPDATE provider_connections SET secret_ciphertext=?,metadata_json=?,updated_at=? WHERE id=?').run(secretCiphertext,JSON.stringify(metadata),now,existing.id);else this.db.prepare('INSERT INTO provider_connections(id,user_id,provider,secret_ciphertext,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(id,userId,provider,secretCiphertext,JSON.stringify(metadata),now,now);return this.getProviderConnection(userId,provider);}
  getProviderConnection(userId,provider){const x=this.db.prepare('SELECT id,user_id,provider,secret_ciphertext,metadata_json,created_at,updated_at FROM provider_connections WHERE user_id=? AND provider=?').get(userId,provider);return x?{...x,metadata:x.metadata_json?JSON.parse(x.metadata_json):{}}:null;}
  listProviderConnections(userId){return this.db.prepare('SELECT id,user_id,provider,metadata_json,created_at,updated_at FROM provider_connections WHERE user_id=? ORDER BY provider').all(userId).map(x=>({...x,metadata:x.metadata_json?JSON.parse(x.metadata_json):{}}));}
  deleteProviderConnection(userId,provider){this.db.prepare('DELETE FROM provider_connections WHERE user_id=? AND provider=?').run(userId,provider);return true;}
  createOAuthState(userId,provider,state,expiresAt,metadata={}){this.db.prepare('DELETE FROM oauth_states WHERE user_id=? AND provider=?').run(userId,provider);const id=randomUUID();this.db.prepare('INSERT INTO oauth_states(id,user_id,provider,state,expires_at,metadata_json,created_at) VALUES (?,?,?,?,?,?,?)').run(id,userId,provider,state,expiresAt,JSON.stringify(metadata),this.now());return id;}
  consumeOAuthState(provider,state){const x=this.db.prepare('SELECT * FROM oauth_states WHERE provider=? AND state=? AND expires_at>?').get(provider,state,this.now());this.db.prepare('DELETE FROM oauth_states WHERE provider=? AND state=?').run(provider,state);return x?{...x,metadata:x.metadata_json?JSON.parse(x.metadata_json):{}}:null;}
  createDeployment(userId,projectId,data={}){const id=randomUUID(),now=this.now();this.db.prepare('INSERT INTO deployments(id,user_id,project_id,provider,status,deployment_id,url,branch,commit_sha,error,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,userId,projectId,String(data.provider),String(data.status||'queued'),data.deploymentId||null,data.url||null,data.branch||null,data.commitSha||null,data.error||null,JSON.stringify(data.metadata||{}),now,now);return this.getDeployment(id,userId);}
  getDeployment(id,userId){const x=this.db.prepare('SELECT * FROM deployments WHERE id=? AND user_id=?').get(id,userId);return x?{...x,metadata:x.metadata_json?JSON.parse(x.metadata_json):{}}:null;}
  listDeployments(projectId,userId){return this.db.prepare('SELECT * FROM deployments WHERE project_id=? AND user_id=? ORDER BY created_at DESC').all(projectId,userId).map(x=>({...x,metadata:x.metadata_json?JSON.parse(x.metadata_json):{}}));}
  updateDeployment(id,userId,patch={}){const fields=[],vals=[];for(const k of ['status','deployment_id','url','branch','commit_sha','error'])if(k in patch){fields.push(k+'=?');vals.push(patch[k]);}if('metadata' in patch){fields.push('metadata_json=?');vals.push(JSON.stringify(patch.metadata||{}));}if(!fields.length)return this.getDeployment(id,userId);fields.push('updated_at=?');vals.push(this.now(),id,userId);this.db.prepare('UPDATE deployments SET '+fields.join(',')+' WHERE id=? AND user_id=?').run(...vals);return this.getDeployment(id,userId);}
  createProjectAsset(projectId,userId,{id=randomUUID(),name,mime,kind,role='other',size,sha256,publicPath,metadata={}}={}){
    if(!this.getProject(projectId,userId))throw new Error('Project not found');const now=this.now();
    this.db.prepare('INSERT INTO project_assets(id,project_id,user_id,name,mime,kind,role,size,sha256,public_path,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,projectId,userId,String(name),String(mime||'application/octet-stream'),String(kind||'binary'),String(role||'other'),Number(size||0),String(sha256||''),String(publicPath||''),JSON.stringify(metadata&&typeof metadata==='object'?metadata:{}),now,now);
    return this.getProjectAsset(id,projectId,userId);
  }
  getProjectAsset(id,projectId,userId){const x=this.db.prepare('SELECT * FROM project_assets WHERE id=? AND project_id=? AND user_id=?').get(id,projectId,userId);return x?({...x,metadata:x.metadata_json?JSON.parse(x.metadata_json):{}}):null;}
  listProjectAssets(projectId,userId){if(!this.getProject(projectId,userId))return [];return this.db.prepare('SELECT * FROM project_assets WHERE project_id=? AND user_id=? ORDER BY created_at DESC').all(projectId,userId).map(x=>({...x,metadata:x.metadata_json?JSON.parse(x.metadata_json):{}}));}
  deleteProjectAsset(id,projectId,userId){const a=this.getProjectAsset(id,projectId,userId);if(!a)return null;this.db.prepare('DELETE FROM project_assets WHERE id=? AND project_id=? AND user_id=?').run(id,projectId,userId);return a;}
  getVisualBaseline(projectId,userId,route){if(!this.getProject(projectId,userId))return null;return this.db.prepare('SELECT * FROM visual_baselines WHERE project_id=? AND user_id=? AND route=?').get(projectId,userId,String(route))||null;}
  listVisualBaselines(projectId,userId){if(!this.getProject(projectId,userId))return [];return this.db.prepare('SELECT * FROM visual_baselines WHERE project_id=? AND user_id=? ORDER BY route').all(projectId,userId);}
  upsertVisualBaseline(projectId,userId,{route,storedPath,size,sha256,width=null,height=null}={}){if(!this.getProject(projectId,userId))throw new Error('Project not found');const now=this.now(),existing=this.getVisualBaseline(projectId,userId,route);if(existing)this.db.prepare('UPDATE visual_baselines SET stored_path=?,size=?,sha256=?,width=?,height=?,updated_at=? WHERE id=? AND project_id=? AND user_id=?').run(storedPath,Number(size||0),sha256,Number.isFinite(Number(width))?Number(width):null,Number.isFinite(Number(height))?Number(height):null,now,existing.id,projectId,userId);else this.db.prepare('INSERT INTO visual_baselines(id,project_id,user_id,route,stored_path,size,sha256,width,height,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),projectId,userId,String(route),String(storedPath),Number(size||0),String(sha256||''),Number.isFinite(Number(width))?Number(width):null,Number.isFinite(Number(height))?Number(height):null,now,now);return this.getVisualBaseline(projectId,userId,route);}
  getProjectContent(projectId,userId){
    const project=this.getProject(projectId,userId);if(!project)return null;
    const row=this.db.prepare('SELECT content_json FROM project_content WHERE project_id=? AND user_id=?').get(projectId,userId);
    if(!row)return null;
    try{return JSON.parse(row.content_json)}catch{return null}
  }
  upsertProjectContent(projectId,userId,content){
    const project=this.getProject(projectId,userId);if(!project)throw new Error('Project not found');
    const normalized=content&&typeof content==='object'?content:{};
    const now=this.now();
    this.db.prepare('INSERT INTO project_content(project_id,user_id,content_json,updated_at) VALUES (?,?,?,?) ON CONFLICT(project_id) DO UPDATE SET user_id=excluded.user_id,content_json=excluded.content_json,updated_at=excluded.updated_at').run(projectId,userId,JSON.stringify(normalized),now);
    this.db.prepare('UPDATE projects SET updated_at=? WHERE id=?').run(now,projectId);
    return this.getProjectContent(projectId,userId);
  }
  createSession(userId,projectId,title='New build'){const p=this.getProject(projectId,userId);if(!p)throw new Error('Project not found');const id=randomUUID(),now=this.now();this.db.prepare('INSERT INTO sessions VALUES (?,?,?,?,?,?)').run(id,projectId,userId,String(title).slice(0,120),now,now);return this.getSession(id,userId);}
  getSession(id,userId){return this.db.prepare('SELECT * FROM sessions WHERE id=? AND user_id=?').get(id,userId)||null;}
  listSessions(projectId,userId){return this.db.prepare('SELECT * FROM sessions WHERE project_id=? AND user_id=? ORDER BY updated_at DESC').all(projectId,userId);}
  createRun(userId,sessionId,request,targetId='web-node'){const id=randomUUID(),now=this.now();this.db.prepare('INSERT INTO runs(id,session_id,user_id,status,request,target_id,spec_json,workspace,preview_url,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(id,sessionId,userId,'running',request,targetId,null,null,null,now,now);return this.getRun(id,userId);}
  updateRun(id,userId,patch){const run=this.getRun(id,userId);if(!run)throw new Error('Run not found');const allowed=['status','target_id','spec_json','workspace','preview_url'];const fields=[],vals=[];for(const k of allowed)if(k in patch){fields.push(`${k}=?`);vals.push(patch[k]);}fields.push('updated_at=?');vals.push(this.now(),id,userId);this.db.prepare(`UPDATE runs SET ${fields.join(',')} WHERE id=? AND user_id=?`).run(...vals);return this.getRun(id,userId);}
  getRun(id,userId){return this.db.prepare('SELECT * FROM runs WHERE id=? AND user_id=?').get(id,userId)||null;}
  listRuns(sessionId,userId){return this.db.prepare('SELECT * FROM runs WHERE session_id=? AND user_id=? ORDER BY created_at DESC').all(sessionId,userId);}
  createChangeset(runId,{status='proposed',summary='',operations=[]}){const id=randomUUID();this.db.prepare('INSERT INTO changesets VALUES (?,?,?,?,?,?,?)').run(id,runId,status,summary,JSON.stringify(operations),null,this.now());return this.getChangeset(id);}
  getChangeset(id){return this.db.prepare('SELECT * FROM changesets WHERE id=?').get(id)||null;}
  listChangesets(runId){return this.db.prepare('SELECT * FROM changesets WHERE run_id=? ORDER BY created_at').all(runId).map(x=>({...x,operations:x.operations_json?JSON.parse(x.operations_json):[]}));}
  updateChangeset(id,patch){const fields=[],vals=[];for(const k of ['status','summary','commit_sha','operations_json'])if(k in patch){fields.push(`${k}=?`);vals.push(k==='operations_json'&&typeof patch[k]!=='string'?JSON.stringify(patch[k]):patch[k]);}if(!fields.length)return this.getChangeset(id);vals.push(id);this.db.prepare(`UPDATE changesets SET ${fields.join(',')} WHERE id=?`).run(...vals);return this.getChangeset(id);}
  addEvidence(runId,type,payload){const id=randomUUID();this.db.prepare('INSERT INTO evidence VALUES (?,?,?,?,?)').run(id,runId,type,JSON.stringify(payload??null),this.now());return {id,runId,type,payload};}
  listEvidence(runId){return this.db.prepare('SELECT * FROM evidence WHERE run_id=? ORDER BY created_at').all(runId).map(x=>({...x,payload:x.payload_json?JSON.parse(x.payload_json):null}));}
  addMessage(sessionId,role,content,metadata={}){const id=randomUUID();this.db.prepare('INSERT INTO messages VALUES (?,?,?,?,?,?)').run(id,sessionId,role,content,JSON.stringify(metadata??{}),this.now());this.db.prepare('UPDATE sessions SET updated_at=? WHERE id=?').run(this.now(),sessionId);return {id,sessionId,role,content,metadata};}
  listMessages(sessionId,userId){return this.db.prepare('SELECT m.* FROM messages m JOIN sessions s ON s.id=m.session_id WHERE m.session_id=? AND s.user_id=? ORDER BY m.created_at').all(sessionId,userId).map(x=>({...x,metadata:x.metadata_json?JSON.parse(x.metadata_json):{}}));}
  addEvent(runId,type,payload){const id=randomUUID();this.db.prepare('INSERT INTO run_events VALUES (?,?,?,?,?)').run(id,runId,type,JSON.stringify(payload??null),this.now());return {id,runId,type,payload};}
  listEvents(runId,userId){const ok=this.getRun(runId,userId);if(!ok)return [];return this.db.prepare('SELECT * FROM run_events WHERE run_id=? ORDER BY created_at').all(runId).map(x=>({...x,payload:x.payload_json?JSON.parse(x.payload_json):null}));}
  toolCall(runId,tool,permission,input,before,after,result){const id=randomUUID();this.db.prepare('INSERT INTO tool_calls VALUES (?,?,?,?,?,?,?,?,?)').run(id,runId,tool,permission,JSON.stringify(input??null),JSON.stringify(before??null),JSON.stringify(after??null),JSON.stringify(result??null),this.now());return id;}
  upsertRunner({id=randomUUID(),name,capability,labels=[],metadata={},status='ready'}={}){const now=this.now();const exists=this.db.prepare('SELECT id FROM runner_nodes WHERE id=?').get(id);if(exists)this.db.prepare('UPDATE runner_nodes SET name=?,capability=?,labels_json=?,metadata_json=?,status=?,last_heartbeat=?,updated_at=? WHERE id=?').run(String(name),String(capability),JSON.stringify(labels),JSON.stringify(metadata),String(status),now,now,id);else this.db.prepare('INSERT INTO runner_nodes(id,name,capability,labels_json,metadata_json,status,last_heartbeat,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').run(id,String(name),String(capability),JSON.stringify(labels),JSON.stringify(metadata),String(status),now,now,now);return this.getRunner(id);}
  heartbeatRunner(id,{status='ready',metadata}={}){const now=this.now();const fields=['status=?','last_heartbeat=?','updated_at=?'];const vals=[String(status),now,now];if(metadata!==undefined){fields.push('metadata_json=?');vals.push(JSON.stringify(metadata));}vals.push(id);this.db.prepare(`UPDATE runner_nodes SET ${fields.join(',')} WHERE id=?`).run(...vals);return this.getRunner(id);}
  getRunner(id){const r=this.db.prepare('SELECT * FROM runner_nodes WHERE id=?').get(id);return r?({...r,labels:r.labels_json?JSON.parse(r.labels_json):[],metadata:r.metadata_json?JSON.parse(r.metadata_json):{}}):null;}
  listRunners({staleMs=120000}={}){const rows=this.db.prepare('SELECT * FROM runner_nodes ORDER BY capability,name').all();const now=Date.now();return rows.map(r=>({...r,labels:r.labels_json?JSON.parse(r.labels_json):[],metadata:r.metadata_json?JSON.parse(r.metadata_json):{},stale:(now-Date.parse(r.last_heartbeat))>staleMs}));}
  createTask({id=randomUUID(),runId,key,title,phase='lifecycle',status='pending',dependencies=[],metadata={}}={}){const now=this.now();this.db.prepare('INSERT INTO agent_tasks(id,run_id,key,title,phase,status,dependencies_json,metadata_json,started_at,finished_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').run(id,runId,String(key),String(title),String(phase),String(status),JSON.stringify(dependencies),JSON.stringify(metadata),status==='running'?now:null,null,now,now);return this.getTask(id);}
  getTask(id){const x=this.db.prepare('SELECT * FROM agent_tasks WHERE id=?').get(id);return x?this.hydrateTask(x):null;}
  getTaskByKey(runId,key){const x=this.db.prepare('SELECT * FROM agent_tasks WHERE run_id=? AND key=?').get(runId,key);return x?this.hydrateTask(x):null;}
  listTasks(runId){return this.db.prepare('SELECT * FROM agent_tasks WHERE run_id=? ORDER BY created_at').all(runId).map(x=>this.hydrateTask(x));}
  hydrateTask(x){return {...x,dependencies:x.dependencies_json?JSON.parse(x.dependencies_json):[],metadata:x.metadata_json?JSON.parse(x.metadata_json):{}};}
  updateTask(id,patch={}){const t=this.getTask(id);if(!t)throw new Error('Task not found');const fields=[],vals=[];for(const k of ['status','phase','title','started_at','finished_at'])if(k in patch){fields.push(`${k}=?`);vals.push(patch[k]);}if('dependencies' in patch){fields.push('dependencies_json=?');vals.push(JSON.stringify(patch.dependencies));}if('metadata' in patch){fields.push('metadata_json=?');vals.push(JSON.stringify(patch.metadata));}if(!fields.length)return t;fields.push('updated_at=?');vals.push(this.now(),id);this.db.prepare(`UPDATE agent_tasks SET ${fields.join(',')} WHERE id=?`).run(...vals);return this.getTask(id);}
  saveRepositoryIndex(runId,index){const now=this.now();this.db.prepare('INSERT INTO repository_indexes(run_id,index_json,created_at,updated_at) VALUES (?,?,?,?) ON CONFLICT(run_id) DO UPDATE SET index_json=excluded.index_json,updated_at=excluded.updated_at').run(runId,JSON.stringify(index),now,now);return index;}
  getRepositoryIndex(runId){const x=this.db.prepare('SELECT index_json FROM repository_indexes WHERE run_id=?').get(runId);return x?JSON.parse(x.index_json):null;}
  createDependencyRequest(runId,dependencies=[]){const existing=this.db.prepare('SELECT * FROM dependency_requests WHERE run_id=? ORDER BY created_at DESC LIMIT 1').get(runId);if(existing&&existing.status==='approved')return existing;const id=randomUUID(),now=this.now();this.db.prepare('INSERT INTO dependency_requests(id,run_id,dependencies_json,status,created_at,updated_at) VALUES (?,?,?,?,?,?)').run(id,runId,JSON.stringify(dependencies),'pending',now,now);return this.getDependencyRequest(id);}
  getDependencyRequest(id){const x=this.db.prepare('SELECT * FROM dependency_requests WHERE id=?').get(id);return x?{...x,dependencies:x.dependencies_json?JSON.parse(x.dependencies_json):[]}:null;}
  getLatestDependencyRequest(runId){const x=this.db.prepare('SELECT * FROM dependency_requests WHERE run_id=? ORDER BY created_at DESC LIMIT 1').get(runId);return x?{...x,dependencies:x.dependencies_json?JSON.parse(x.dependencies_json):[]}:null;}
  approveDependencyRequest(id,userId){const x=this.getDependencyRequest(id);if(!x)return null;const run=this.getRun(x.run_id,userId);if(!run)throw new Error('not_found');this.db.prepare("UPDATE dependency_requests SET status='approved',approved_at=?,approved_by=?,updated_at=? WHERE id=?").run(this.now(),userId,this.now(),id);return this.getDependencyRequest(id);}
  listDependencyRequests(runId,userId){if(!this.getRun(runId,userId))return [];return this.db.prepare('SELECT * FROM dependency_requests WHERE run_id=? ORDER BY created_at').all(runId).map(x=>({...x,dependencies:x.dependencies_json?JSON.parse(x.dependencies_json):[]}));}
  addUsage(runId,userId,usage={}){const id=randomUUID();this.db.prepare('INSERT INTO usage_events(id,run_id,user_id,provider,model,tier,input_tokens,output_tokens,tool_calls,duration_ms,estimated_cost_usd,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').run(id,runId,userId,usage.provider||null,usage.model||null,usage.tier||null,Number(usage.inputTokens||0),Number(usage.outputTokens||0),Number(usage.toolCalls||0),Number(usage.durationMs||0),usage.estimatedCostUsd==null?null:Number(usage.estimatedCostUsd),this.now());return id;}
  listUsage(runId,userId){if(!this.getRun(runId,userId))return [];return this.db.prepare('SELECT * FROM usage_events WHERE run_id=? ORDER BY created_at').all(runId);}
  usageSummary(runId,userId){if(!this.getRun(runId,userId))return null;const x=this.db.prepare('SELECT COUNT(*) calls,COALESCE(SUM(input_tokens),0) input_tokens,COALESCE(SUM(output_tokens),0) output_tokens,COALESCE(SUM(tool_calls),0) tool_calls,COALESCE(SUM(duration_ms),0) duration_ms,SUM(estimated_cost_usd) estimated_cost_usd FROM usage_events WHERE run_id=?').get(runId);return {...x,estimated_cost_usd:x.estimated_cost_usd==null?null:Number(x.estimated_cost_usd)};}
  createCheckpoint(runId,name,pathValue,metadata={}){const id=randomUUID();this.db.prepare('INSERT INTO run_checkpoints(id,run_id,name,path,metadata_json,created_at) VALUES (?,?,?,?,?,?)').run(id,runId,String(name).slice(0,120),pathValue,JSON.stringify(metadata),this.now());return this.getCheckpoint(id);}
  createGoal(runId,{objective,completionCriteria=[],constraints=[],status='active',metadata={}}={}){const now=this.now(),id=randomUUID();this.db.prepare('INSERT INTO run_goals(id,run_id,objective,completion_criteria_json,constraints_json,status,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').run(id,runId,String(objective||''),JSON.stringify(completionCriteria),JSON.stringify(constraints),status,JSON.stringify(metadata),now,now);return this.getGoal(runId);}
  getGoal(runId){const x=this.db.prepare('SELECT * FROM run_goals WHERE run_id=?').get(runId);return x?{...x,completionCriteria:x.completion_criteria_json?JSON.parse(x.completion_criteria_json):[],constraints:x.constraints_json?JSON.parse(x.constraints_json):[],metadata:x.metadata_json?JSON.parse(x.metadata_json):{}}:null;}
  updateGoal(runId,patch={}){const fields=[],vals=[];for(const k of ['objective','status'])if(k in patch){fields.push(`${k}=?`);vals.push(patch[k]);}if('completionCriteria' in patch){fields.push('completion_criteria_json=?');vals.push(JSON.stringify(patch.completionCriteria));}if('constraints' in patch){fields.push('constraints_json=?');vals.push(JSON.stringify(patch.constraints));}if('metadata' in patch){fields.push('metadata_json=?');vals.push(JSON.stringify(patch.metadata));}if(!fields.length)return this.getGoal(runId);fields.push('updated_at=?');vals.push(this.now(),runId);this.db.prepare(`UPDATE run_goals SET ${fields.join(',')} WHERE run_id=?`).run(...vals);return this.getGoal(runId);}
  getCheckpoint(id){const row=this.db.prepare('SELECT * FROM run_checkpoints WHERE id=?').get(id);return row?{...row,metadata:row.metadata_json?JSON.parse(row.metadata_json):{}}:null;}
  listCheckpoints(runId){return this.db.prepare('SELECT * FROM run_checkpoints WHERE run_id=? ORDER BY created_at').all(runId).map(x=>({...x,metadata:x.metadata_json?JSON.parse(x.metadata_json):{}}));}
  recordArtifact(runId,{type='binary',path,size=0,sha256,storedPath=null,url=null}){const id=randomUUID();this.db.prepare('INSERT INTO artifacts(id,run_id,type,path,size,sha256,stored_path,url,created_at) VALUES (?,?,?,?,?,?,?,?,?)').run(id,runId,String(type),String(path),Number(size)||0,String(sha256||''),storedPath,url,this.now());return this.getArtifact(id);}
  getArtifact(id){return this.db.prepare('SELECT * FROM artifacts WHERE id=?').get(id)||null;}
  listArtifacts(runId){return this.db.prepare('SELECT * FROM artifacts WHERE run_id=? ORDER BY created_at').all(runId);}
  close(){this.db.close();}
}
