export async function browserSmoke(baseUrl,paths,{screenshots=false,artifactDir='artifacts',viewport={width:1440,height:900}}={}){
 let pw;try{pw=await import('playwright');}catch{return{enabled:true,available:false,passed:false,skipped:'playwright not installed',results:[]};}
 const fs=await import('node:fs');fs.mkdirSync(artifactDir,{recursive:true});const browser=await pw.chromium.launch({headless:true});const results=[];
 try{
  for(const p of paths){const page=await browser.newPage({viewport});const consoleErrors=[],consoleWarnings=[],requestFailures=[],responseFailures=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());if(m.type()==='warning')consoleWarnings.push(m.text())});page.on('requestfailed',r=>requestFailures.push({url:r.url(),failure:r.failure()?.errorText||'request failed'}));page.on('response',r=>{if(r.status()>=500)responseFailures.push({url:r.url(),status:r.status()});});
   let status=0,error=null,ui={},screenshot=null,domSnapshot=null;
   try{
    const r=await page.goto(new URL(p,baseUrl).toString(),{waitUntil:'networkidle',timeout:15000});status=r?.status()||0;
    const links=await page.locator('a[href]').evaluateAll(els=>els.map(e=>e.getAttribute('href')).filter(Boolean).filter(x=>x.startsWith('/')));for(const link of links){const response=await fetch(new URL(link,baseUrl));if(!(response.status>=200&&response.status<400))requestFailures.push({url:response.url(),failure:`internal link ${response.status}`});}
    ui=await page.evaluate(()=>{const images=[...document.images];const buttons=[...document.querySelectorAll('button,input[type="button"],input[type="submit"]')];const links=[...document.querySelectorAll('a[href]')];const rect=document.documentElement.getBoundingClientRect();const text=document.body?.innerText||'';return{title:document.title||'',lang:document.documentElement.lang||'',viewport:!!document.querySelector('meta[name="viewport"]'),main:!!document.querySelector('main'),h1:document.querySelectorAll('h1').length,imagesWithoutAlt:images.filter(x=>!x.getAttribute('alt')).length,controlsWithoutName:buttons.filter(x=>!(x.getAttribute('aria-label')||x.textContent?.trim()||x.getAttribute('title'))).length,linksWithoutName:links.filter(x=>!(x.getAttribute('aria-label')||x.textContent?.trim()||x.getAttribute('title'))).length,documentWidth:rect.width,bodyScrollWidth:document.body?.scrollWidth||rect.width,bodyTextLength:text.length,forms:document.querySelectorAll('form').length};});
    if(screenshots){const safe=encodeURIComponent(p.slice(1)||'home');screenshot=`${artifactDir}/${safe}.png`;domSnapshot=`${artifactDir}/${safe}.html`;await page.screenshot({path:screenshot,fullPage:true});fs.writeFileSync(domSnapshot,await page.content(),'utf8');}
   }catch(e){error=e.message;}
   const uiFailures=[];if(!ui.title)uiFailures.push('missing document title');if(!ui.lang)uiFailures.push('missing html lang');if(ui.viewport===false)uiFailures.push('missing responsive viewport');if(ui.imagesWithoutAlt>0)uiFailures.push(`${ui.imagesWithoutAlt} image(s) without alt text`);if(ui.controlsWithoutName>0)uiFailures.push(`${ui.controlsWithoutName} control(s) without accessible name`);if(ui.linksWithoutName>0)uiFailures.push(`${ui.linksWithoutName} link(s) without accessible name`);if(ui.bodyScrollWidth>ui.documentWidth+4)uiFailures.push('horizontal overflow detected');
   await page.close();results.push({path:p,status,consoleErrors,consoleWarnings,requestFailures,responseFailures,error,ui,uiFailures,screenshot,domSnapshot,ok:!error&&status>=200&&status<400&&consoleErrors.length===0&&requestFailures.length===0&&responseFailures.length===0&&uiFailures.length===0});
  }
 }finally{await browser.close();}
 return{enabled:true,available:true,passed:results.every(x=>x.ok),results,uiQuality:{pages:results.length,passed:results.filter(x=>x.uiFailures.length===0).length,failures:results.flatMap(x=>x.uiFailures.map(f=>`${x.path}: ${f}`))},debug:{consoleErrors:results.reduce((n,x)=>n+x.consoleErrors.length,0),requestFailures:results.reduce((n,x)=>n+x.requestFailures.length,0),serverErrors:results.reduce((n,x)=>n+x.responseFailures.length,0)}};
}
