import {configuredConnectors,getConnectorDefinition,parseProviderChain,resolveConnector,listConnectorDefinitions} from './connectors.js';
import {estimateCostUsd} from './pricing.js';
function json(value){return JSON.stringify(value);}
function parseProfiles(env){try{const raw=JSON.parse(env.CODINGVIBES_MODEL_PROFILES||'{}');return raw&&typeof raw==='object'?raw:{};}catch{return{};}}
function isAbort(e){return e?.name==='AbortError'||e?.code==='ABORT_ERR'||/aborted|cancelled/i.test(String(e?.message||''));}

export class ModelRouter{
  constructor(env=process.env){
    this.env=env;this.profiles=parseProfiles(env);this.chain=parseProviderChain(env);this.health=new Map();
    this.models={cheap:env.CODINGVIBES_MODEL_CHEAP||'gpt-4o-mini',standard:env.CODINGVIBES_MODEL_STANDARD||'gpt-4o-mini',premium:env.CODINGVIBES_MODEL_PREMIUM||'gpt-4.1'};
    this.cooldownMs=Number(env.CODINGVIBES_PROVIDER_COOLDOWN_MS||15_000);
  }
  resolveProvider(provider){return resolveConnector(provider||this.chain[0],this.env);}
  resolveModel(tier,provider){const c=this.resolveProvider(provider),profile=this.profiles[c.id]||{};return profile.models?.[tier]||this.env[`CODINGVIBES_MODEL_${String(tier).toUpperCase()}`]||c.models?.[tier]||this.models[tier]||this.models.standard;}
  requiresKey(provider){return !['ollama','lmstudio'].includes(provider.id)&&Boolean(provider.apiKeyEnv);}
  getStatus(){const primary=this.resolveProvider(this.chain[0]);return{provider:primary.id,chain:this.chain,baseUrl:primary.baseUrl,configured:this.candidates().length>0,protocol:primary.protocol,models:{cheap:this.resolveModel('cheap',primary.id),standard:this.resolveModel('standard',primary.id),premium:this.resolveModel('premium',primary.id)},streaming:true,connectors:configuredConnectors(this.env).map(c=>({id:c.id,label:c.label,kind:c.kind,protocol:c.protocol,baseUrl:c.baseUrl,configured:c.configured}))};}
  listConnectors(){return listConnectorDefinitions().map(d=>{const c=resolveConnector(d.id,this.env);return{...d,configured:c.configured,baseUrl:c.baseUrl,requiresKey:Boolean(d.apiKeyEnv),health:this.health.get(d.id)||null};});}
  headers(provider){const h={'content-type':'application/json'};if(provider.protocol==='anthropic-messages'){if(provider.apiKey)h['x-api-key']=provider.apiKey;h['anthropic-version']='2023-06-01';return h;}if(provider.apiKey)h.authorization=`Bearer ${provider.apiKey}`;if(provider.id==='openrouter'){h['HTTP-Referer']=this.env.CODINGVIBES_APP_URL||'http://localhost:4400';h['X-Title']='codingVibes';}return h;}
  markFailure(id,error){const h=this.health.get(id)||{failures:0};const failures=h.failures+1;this.health.set(id,{failures,lastError:String(error?.message||error).slice(0,300),retryAt:Date.now()+this.cooldownMs*Math.min(failures,5)});}
  markSuccess(id){this.health.set(id,{failures:0,lastSuccess:Date.now(),retryAt:0});}
  async testConnection(providerId,{signal}={}){const provider=this.resolveProvider(providerId);if(!provider.baseUrl)return{ok:false,error:'base_url_required',provider:provider.id};if(this.requiresKey(provider)&&!provider.apiKey)return{ok:false,error:'api_key_required',provider:provider.id};try{const r=await fetch(`${provider.baseUrl}/models`,{headers:this.headers(provider),signal});if(!r.ok)return{ok:false,error:`HTTP ${r.status}`,status:r.status,provider:provider.id};const j=await r.json().catch(()=>({}));this.markSuccess(provider.id);return{ok:true,provider:provider.id,baseUrl:provider.baseUrl,models:Array.isArray(j.data)?j.data.map(x=>x.id).slice(0,100):[]};}catch(e){if(!isAbort(e))this.markFailure(provider.id,e);return{ok:false,error:e.message,provider:provider.id};}}
  candidates(preferred){const ids=[preferred,...this.chain];const now=Date.now();return[...new Set(ids.filter(Boolean))].map(id=>this.resolveProvider(id)).filter(c=>{if(!(c.configured||!this.requiresKey(c)))return false;const h=this.health.get(c.id);return !h?.retryAt||h.retryAt<=now;});}
  async complete({system,user,tier='standard',temperature=0,provider,model,onUsage=()=>{},signal}={}){let lastError=null;let available=this.candidates(provider);if(!available.length&&this.candidates(provider).length===0)return{provider:'fallback',model:'deterministic',text:null};for(const candidate of available){const chosenModel=model||this.resolveModel(tier,candidate.id);try{const started=Date.now();if(candidate.protocol==='anthropic-messages'){
        const r=await fetch(`${candidate.baseUrl}/messages`,{method:'POST',headers:this.headers(candidate),signal,body:json({model:chosenModel,max_tokens:8192,system,messages:[{role:'user',content:user}]})});
        if(!r.ok)throw new Error(`Model request failed: ${r.status} ${await r.text()}`);const j=await r.json();const usage={inputTokens:j.usage?.input_tokens||0,outputTokens:j.usage?.output_tokens||0,durationMs:Date.now()-started};this.markSuccess(candidate.id);onUsage({...usage,provider:candidate.id,model:chosenModel,tier,estimatedCostUsd:estimateCostUsd({model:chosenModel,...usage,env:this.env})});return{provider:candidate.id,model:chosenModel,text:(j.content||[]).filter(x=>x.type==='text').map(x=>x.text).join(''),usage};
      }
      const r=await fetch(`${candidate.baseUrl}/chat/completions`,{method:'POST',headers:this.headers(candidate),signal,body:json({model:chosenModel,messages:[{role:'system',content:system},{role:'user',content:user}],temperature})});
      if(!r.ok)throw new Error(`Model request failed: ${r.status} ${await r.text()}`);const j=await r.json();const usage={inputTokens:j.usage?.prompt_tokens||0,outputTokens:j.usage?.completion_tokens||0,durationMs:Date.now()-started};this.markSuccess(candidate.id);onUsage({...usage,provider:candidate.id,model:chosenModel,tier,estimatedCostUsd:estimateCostUsd({model:chosenModel,...usage,env:this.env})});return{provider:candidate.id,model:chosenModel,text:j.choices?.[0]?.message?.content||'',usage};
    }catch(e){lastError=e;if(isAbort(e))throw Object.assign(new Error('run_cancelled'),{code:'RUN_CANCELLED',cause:e});this.markFailure(candidate.id,e);}}
    throw lastError||new Error('No configured model connector');
  }
  async stream({system,user,tier='standard',temperature=0,onToken=()=>{},onUsage=()=>{},provider,model,signal}={}){let lastError=null;for(const candidate of this.candidates(provider)){let emitted=false;try{const out=await this.streamOne({candidate,system,user,tier,temperature,onToken:onTokenToken=>{emitted=true;onToken(onTokenToken);},onUsage,model,signal});this.markSuccess(candidate.id);return out;}catch(e){lastError=e;if(isAbort(e))throw Object.assign(new Error('run_cancelled'),{code:'RUN_CANCELLED',cause:e});if(emitted)throw e;this.markFailure(candidate.id,e);}}
    if(this.candidates(provider).length===0)return{provider:'fallback',model:'deterministic'};throw lastError||new Error('No configured model connector');}
  async streamOne({candidate,system,user,tier,temperature,onToken,onUsage,model,signal}){const chosenModel=model||this.resolveModel(tier,candidate.id),started=Date.now();if(candidate.protocol==='anthropic-messages')return this.streamAnthropic({candidate,system,user,model:chosenModel,tier,onToken,onUsage,started,signal});
    const r=await fetch(`${candidate.baseUrl}/chat/completions`,{method:'POST',headers:this.headers(candidate),signal,body:json({model:chosenModel,messages:[{role:'system',content:system},{role:'user',content:user}],temperature,stream:true,stream_options:{include_usage:true}})});if(!r.ok)throw new Error(`Model stream failed: ${r.status} ${await r.text()}`);const reader=r.body.getReader();const decoder=new TextDecoder();let buffer='',usage={inputTokens:0,outputTokens:0,durationMs:0};while(true){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){const s=line.trim();if(!s.startsWith('data:'))continue;const data=s.slice(5).trim();if(data==='[DONE]'){usage.durationMs=Date.now()-started;onUsage({...usage,provider:candidate.id,model:chosenModel,tier,estimatedCostUsd:estimateCostUsd({model:chosenModel,...usage,env:this.env})});return{provider:candidate.id,model:chosenModel,usage};}if(!data)continue;try{const chunk=JSON.parse(data);const delta=chunk.choices?.[0]?.delta?.content||'';if(delta)onToken(delta);if(chunk.usage){usage.inputTokens=chunk.usage.prompt_tokens||0;usage.outputTokens=chunk.usage.completion_tokens||0;}}catch{}}}usage.durationMs=Date.now()-started;onUsage({...usage,provider:candidate.id,model:chosenModel,tier,estimatedCostUsd:estimateCostUsd({model:chosenModel,...usage,env:this.env})});return{provider:candidate.id,model:chosenModel,usage};}
  async streamAnthropic({candidate,system,user,model,tier,onToken,onUsage,started,signal}){const r=await fetch(`${candidate.baseUrl}/messages`,{method:'POST',headers:this.headers(candidate),signal,body:json({model,max_tokens:8192,system,messages:[{role:'user',content:user}],stream:true})});if(!r.ok)throw new Error(`Model stream failed: ${r.status} ${await r.text()}`);const reader=r.body.getReader();const decoder=new TextDecoder();let buffer='',inputTokens=0,outputTokens=0;while(true){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){const s=line.trim();if(!s.startsWith('data:'))continue;const data=s.slice(5).trim();if(!data)continue;try{const event=JSON.parse(data);if(event.message?.usage){inputTokens=event.message.usage.input_tokens||inputTokens;outputTokens=event.message.usage.output_tokens||outputTokens;}if(event.type==='message_delta'&&event.usage?.output_tokens)outputTokens=event.usage.output_tokens;if(event.type==='content_block_delta'&&event.delta?.type==='text_delta'&&event.delta.text)onToken(event.delta.text);if(event.type==='message_stop'){const usage={inputTokens,outputTokens,durationMs:Date.now()-started};onUsage({...usage,provider:candidate.id,model,tier,estimatedCostUsd:estimateCostUsd({model,...usage,env:this.env})});return{provider:candidate.id,model,usage};}}catch{}}}const usage={inputTokens,outputTokens,durationMs:Date.now()-started};onUsage({...usage,provider:candidate.id,model,tier,estimatedCostUsd:estimateCostUsd({model,...usage,env:this.env})});return{provider:candidate.id,model,usage};}
}
