function esc(v){return String(v??'').replaceAll('\\','\\\\').replaceAll('`','\\`').replaceAll('${','\\${').replaceAll("'","\\'");}
function title(spec){return esc(spec?.siteTemplateLabel||spec?.request||'Your App').slice(0,120);}
export function expoApp(spec){
 const t=title(spec);
 const features=JSON.stringify((spec?.components||[]).filter(Boolean).slice(0,8));
 return `import React,{useState}from'react';
import{SafeAreaView,StatusBar,ScrollView,StyleSheet,Text,View,Pressable}from'react-native';
const tabs=['Home','Explore','Profile'];const features=${features};
export default function App(){const[tab,setTab]=useState('Home');return <SafeAreaView style={s.safe}><StatusBar barStyle='light-content'/><View style={s.header}><View><Text style={s.kicker}>BUILD VIBE</Text><Text style={s.brand} numberOfLines={1}>${t}</Text></View><View style={s.status}><Text style={s.statusText}>Ready</Text></View></View><ScrollView contentContainerStyle={s.scroll}>{tab==='Home'?<><View style={s.hero}><Text style={s.eyebrow}>BUILT FROM YOUR REQUIREMENTS</Text><Text style={s.heroTitle}>${t}</Text><Text style={s.body}>A polished mobile experience with clear actions and reusable product surfaces.</Text><Pressable style={({pressed})=>[s.cta,pressed&&s.pressed]}><Text style={s.ctaText}>Get started</Text></Pressable></View><Text style={s.section}>Core experience</Text><View style={s.grid}>{features.slice(0,6).map((x,i)=><View key={String(x)+i} style={s.card}><Text style={s.cardIndex}>0{i+1}</Text><Text style={s.cardTitle}>{x}</Text><Text style={s.cardBody}>Reusable product surface.</Text></View>)}</View></>:<View style={s.page}><Text style={s.section}>{tab}</Text><View style={s.card}><Text style={s.cardTitle}>{tab} experience</Text><Text style={s.cardBody}>Ready for the product-specific data and workflows from the application contract.</Text></View></View>}</ScrollView><View style={s.nav}>{tabs.map(x=><Pressable key={x} onPress={()=>setTab(x)} style={({pressed})=>[s.navItem,tab===x&&s.navActive,pressed&&s.pressed]}><Text style={[s.navText,tab===x&&s.navTextActive]}>{x}</Text></Pressable>)}</View></SafeAreaView>)}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#080d17'},scroll:{padding:20,paddingBottom:30},header:{padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#1c2a40'},kicker:{fontSize:10,fontWeight:'800',letterSpacing:2,color:'#8ea8ff'},brand:{color:'#f4f7fb',fontSize:20,fontWeight:'800',maxWidth:260},status:{paddingHorizontal:10,paddingVertical:7,borderRadius:999,borderWidth:1,borderColor:'#31533f',backgroundColor:'#10251a'},statusText:{color:'#8af1b2',fontSize:10,fontWeight:'800'},hero:{marginTop:18,padding:22,borderRadius:28,backgroundColor:'#101a2b',borderWidth:1,borderColor:'#263758'},eyebrow:{fontSize:10,fontWeight:'800',letterSpacing:2,color:'#8ea8ff'},heroTitle:{marginTop:12,color:'#fff',fontSize:36,lineHeight:41,fontWeight:'800'},body:{marginTop:12,color:'#aebbd1',fontSize:14,lineHeight:22},cta:{marginTop:22,alignSelf:'flex-start',paddingHorizontal:18,paddingVertical:13,borderRadius:14,backgroundColor:'#d9f7e2'},ctaText:{color:'#08131a',fontSize:13,fontWeight:'800'},pressed:{opacity:.82},section:{marginTop:24,marginBottom:10,color:'#f1f5fb',fontSize:18,fontWeight:'800'},grid:{gap:10},card:{padding:17,borderRadius:19,backgroundColor:'#0e1727',borderWidth:1,borderColor:'#22324d'},cardIndex:{color:'#67789a',fontSize:10,fontWeight:'800'},cardTitle:{marginTop:8,color:'#edf3ff',fontSize:16,fontWeight:'800'},cardBody:{marginTop:6,color:'#8998b2',fontSize:12,lineHeight:18},page:{minHeight:500},nav:{flexDirection:'row',padding:10,borderTopWidth:1,borderTopColor:'#1c2a40',backgroundColor:'#090f1a'},navItem:{flex:1,alignItems:'center',paddingVertical:10,borderRadius:12},navActive:{backgroundColor:'#17243a'},navText:{color:'#71819e',fontSize:11,fontWeight:'700'},navTextActive:{color:'#fff'}});`;
}
