import {hash} from '../core/hash.js';
import {expoApp} from './app-shells.js';

function json(value){return JSON.stringify(value,null,2)+'\n';}
function commonReadme(spec,target){return `# Generated codingVibes app\n\nTarget: ${target.label}\nLanguage: ${target.language}\nFramework: ${target.framework}\n\nThis project was generated from a structured application contract. Build artifacts are only marked verified when the target toolchain and verification checks succeed.\n\nPages: ${spec.pages.join(', ') || '/'}\n\nAPIs: ${spec.apis.map(x=>`${x.method} ${x.path}`).join(', ') || 'none'}\n`}

function pwaExtras(){return [
  {path:'public/manifest.webmanifest',content:json({name:'codingVibes app',short_name:'codingVibes',start_url:'/',display:'standalone',background_color:'#0b1020',theme_color:'#0b1020',icons:[]})},
  {path:'public/sw.js',content:`self.addEventListener('install',()=>self.skipWaiting());self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith(fetch(e.request).catch(()=>caches.match(e.request)));});\n`},
];}

export function generateTargetFallback(spec,target){
  const files=[];
  if(target.id==='web-pwa')return null;
  if(target.id==='android-twa')return {files:[
    {path:'android/settings.gradle',content:`pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }
rootProject.name='codingvibes-twa'
include ':app'
`},
    {path:'android/build.gradle',content:`plugins { id 'com.android.application' version '8.7.3' apply false }
`},
    {path:'android/app/build.gradle',content:`plugins { id 'com.android.application' }
android { namespace 'com.codingvibes.twa'; compileSdk 36
 defaultConfig { applicationId 'com.codingvibes.twa'; minSdk 23; targetSdk 36; versionCode 1; versionName '1.0' }
}
dependencies { implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.6.2' }
`},
    {path:'android/app/src/main/res/values/strings.xml',content:`<resources><string name="app_name">codingVibes</string><string name="launchUrl">https://example.com/</string></resources>
`},
    {path:'android/gradle.properties',content:`android.useAndroidX=true\nandroid.enableJetifier=false\n`},
    {path:'android/app/src/main/AndroidManifest.xml',content:`<manifest xmlns:android="http://schemas.android.com/apk/res/android"><application android:theme="@android:style/Theme.DeviceDefault.Light.NoActionBar" android:label="@string/app_name"><activity android:name="com.google.androidbrowserhelper.trusted.LauncherActivity" android:exported="true"><meta-data android:name="android.support.customtabs.trusted.DEFAULT_URL" android:value="@string/launchUrl"/><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity></application></manifest>
`},
    {path:'README.md',content:commonReadme(spec,target)+'\nSet the trusted web origin in strings.xml and configure Digital Asset Links for production trust. Then build with Android Gradle tooling.\n'},
  ],summary:`Generate ${target.label}`,manifestHash:hash(spec),source:'deterministic'};
  if(target.id==='mobile-expo')return {files:[
    {path:'package.json',content:json({name:'codingvibes-mobile',version:'0.1.0',private:true,scripts:{check:'tsc --noEmit',test:'node --test test/smoke.test.js','export:web':'expo export --platform web'},dependencies:{expo:'^57.0.0','react':'19.2.3','react-dom':'19.2.3','react-native':'0.86.0','react-native-web':'0.21.0','@expo/metro-runtime':'~6.1.0'},devDependencies:{typescript:'^5.9.2'}})},
    {path:'app.json',content:json({expo:{name:'codingVibes App',slug:'codingvibes-app',version:'1.0.0',orientation:'portrait',platforms:['android','ios'],userInterfaceStyle:'automatic',android:{package:'com.codingvibes.app'},ios:{bundleIdentifier:'com.codingvibes.app'}}})},
    {path:'tsconfig.json',content:json({extends:'expo/tsconfig.base',compilerOptions:{strict:true,noEmit:true},include:['**/*.ts','**/*.tsx']})},
    {path:'eas.json',content:json({build:{development:{developmentClient:true,distribution:'internal'},preview:{distribution:'internal',android:{buildType:'apk'}},production:{}}})},
    {path:'App.tsx',content:expoApp(spec,target)},
    {path:'test/smoke.test.js',content:`import test from'node:test';import assert from'node:assert/strict';test('mobile source exists',()=>assert.ok(true));\n`},
    {path:'README.md',content:commonReadme(spec,target)+'\nUse Expo/EAS or a configured Android/iOS toolchain to produce platform binaries.\n'},
  ],summary:`Generate ${target.label}`,manifestHash:hash(spec),source:'deterministic'};
  if(target.id==='mobile-flutter')return {files:[
    {path:'pubspec.yaml',content:`name: codingvibes_app
description: Generated by codingVibes
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
`},
    {path:'lib/main.dart',content:`import 'package:flutter/material.dart';
void main()=>runApp(const CodingVibesApp());
class CodingVibesApp extends StatefulWidget{const CodingVibesApp({super.key});@override State<CodingVibesApp> createState()=>_CodingVibesAppState();}
class _CodingVibesAppState extends State<CodingVibesApp>{
 int index=0;
 final titles=const ['Home','Explore','Profile'];
 @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),home:Scaffold(appBar:AppBar(title:Text(titles[index])),body:ListView(padding:const EdgeInsets.all(20),children:[Text(index==0?'Your product starts here':index==1?'Explore your local content':'Manage your account',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w700)),const SizedBox(height:12),Card(child:Padding(padding:const EdgeInsets.all(18),child:Text('\${escapeForCode(spec.request.slice(0,180))}'))),const SizedBox(height:12),Wrap(spacing:10,runSpacing:10,children:const [Chip(label:Text('Ready')),Chip(label:Text('Local-first')),Chip(label:Text('Offline-safe UI'))]),const SizedBox(height:12),FilledButton(onPressed:(){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Action saved locally.')));},child:const Text('Get started'))]),bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(i)=>setState(()=>index=i),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.explore_outlined),selectedIcon:Icon(Icons.explore),label:'Explore'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Profile')])));}
}
`},
    {path:'test/widget_test.dart',content:`import 'package:flutter_test/flutter_test.dart';import 'package:codingvibes_app/main.dart';void main(){testWidgets('app mounts',(tester)async{await tester.pumpWidget(const CodingVibesApp());expect(find.text('Home'),findsOneWidget);expect(find.text('Get started'),findsOneWidget);});}
`},
    {path:'README.md',content:commonReadme(spec,target)+'\nRun `flutter analyze`, `flutter test`, then `flutter build apk` or `flutter build appbundle`.\n'},
  ],summary:`Generate \${target.label}`,manifestHash:hash(spec),source:'deterministic'};if(target.id==='android-kotlin')return {files:[
    {path:'settings.gradle.kts',content:`pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }
rootProject.name = "codingvibes-app"
include(":app")
`},
    {path:'build.gradle.kts',content:`plugins { id("com.android.application") version "8.7.3" apply false; id("org.jetbrains.kotlin.android") version "2.0.21" apply false }
`},
    {path:'app/build.gradle.kts',content:`plugins { id("com.android.application"); id("org.jetbrains.kotlin.android") }
android { namespace = "com.codingvibes.app"; compileSdk = 35
 defaultConfig { applicationId = "com.codingvibes.app"; minSdk = 26; targetSdk = 35; versionCode = 1; versionName = "1.0" } }
`},
    {path:'app/src/main/AndroidManifest.xml',content:`<manifest xmlns:android="http://schemas.android.com/apk/res/android"><application android:theme="@android:style/Theme.Material.Light.NoActionBar" android:label="codingVibes"><activity android:name=".MainActivity" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity></application></manifest>\n`},
    {path:'app/src/main/java/MainActivity.kt',content:`package com.codingvibes.app
import android.app.Activity
import android.os.Bundle
import android.graphics.Color
import android.view.Gravity
import android.widget.Button
import android.widget.LinearLayout
import android.widget.TextView
class MainActivity: Activity(){
 override fun onCreate(savedInstanceState:Bundle?){
  super.onCreate(savedInstanceState)
  val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(32,32,32,32);setBackgroundColor(Color.WHITE)}
  val title=TextView(this).apply{text="codingVibes";textSize=28f;setTextColor(Color.BLACK)}
  val subtitle=TextView(this).apply{text="\${escapeForCode(spec.request.slice(0,180))}";textSize=17f;setTextColor(Color.DKGRAY);setPadding(0,12,0,20)}
  val status=TextView(this).apply{text="Home";textSize=22f;gravity=Gravity.CENTER_VERTICAL}
  val nav=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL}
  fun navButton(label:String,onClick:()->Unit)=Button(this).apply{text=label;setOnClickListener{onClick()}}
  nav.addView(navButton("Home"){status.text="Home"})
  nav.addView(navButton("Calendar"){status.text="Calendar"})
  nav.addView(navButton("Settings"){status.text="Settings"})
  root.addView(title);root.addView(subtitle);root.addView(status,LinearLayout.LayoutParams(-1,90));root.addView(nav)
  root.addView(Button(this).apply{text="Get started";setOnClickListener{status.text="Saved locally"}})
  setContentView(root)
 }
}
`},
    {path:'README.md',content:commonReadme(spec,target)+'\nRun the Gradle wrapper with the Android SDK to produce a debug APK/AAB. The shell is local-first and does not require a hosted API.\n'},
  ],summary:`Generate \${target.label}`,manifestHash:hash(spec),source:'deterministic'};if(target.id==='ios-swiftui')return {files:[
    {path:'Package.swift',content:`// swift-tools-version: 6.0
import PackageDescription
let package=Package(name:"CodingVibesApp",platforms:[.iOS(.v17)],products:[.library(name:"CodingVibesApp",targets:["App"])],targets:[.target(name:"App")])
`},
    {path:'Sources/App/App.swift',content:`import SwiftUI
public struct ContentView:View{
 public init(){}
 public var body:some View{
  TabView{
   NavigationStack{List{Section("Home"){Text("\${escapeForCode(spec.request.slice(0,180))}");Label("Local-first product shell",systemImage:"shippingbox");Button("Get started"){}}}.navigationTitle("Home")}.tabItem{Label("Home",systemImage:"house")}
   NavigationStack{List{Text("Explore");Text("Your records and collections will appear here.");Text("Loading, empty and error states are handled by the product contract.")}.navigationTitle("Explore")}.tabItem{Label("Explore",systemImage:"safari")}
   NavigationStack{List{Text("Profile");Text("Account and settings stay in the product shell.")}.navigationTitle("Profile")}.tabItem{Label("Profile",systemImage:"person")}
  }
 }
}
#if os(iOS)
@main struct CodingVibesApp:App{var body:some Scene{WindowGroup{ContentView()}}}
#endif
`},
    {path:'README.md',content:commonReadme(spec,target)+'\nOpen in Xcode for simulator/build/archive workflows. Linux can validate the Swift package source only; iOS signing requires Apple tooling.\n'},
  ],summary:`Generate \${target.label}`,manifestHash:hash(spec),source:'deterministic'};if(target.id==='desktop-electron')return {files:[
    {path:'package.json',content:json({name:'codingvibes-desktop',version:'0.1.0',private:true,type:'module',main:'src/main.js',scripts:{start:'electron .',check:'node --check src/main.js',test:'node --test test/smoke.test.js'},devDependencies:{electron:'^37.0.0'}})},
    {path:'src/main.js',content:`import{app,BrowserWindow}from'electron';import path from'node:path';const create=()=>{const w=new BrowserWindow({width:1280,height:820,minWidth:900,minHeight:650,show:false});w.once('ready-to-show',()=>w.show());w.loadFile(path.join(process.cwd(),'src/index.html'));};app.whenReady().then(create);app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});\n`},
    {path:'src/index.html',content:`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>codingVibes desktop</title><style>body{font-family:system-ui;margin:0;background:#f6f7fb;color:#131722}main{max-width:1100px;margin:auto;padding:40px 24px}.nav{display:flex;gap:8px;flex-wrap:wrap}.nav button{border:0;border-radius:12px;padding:10px 14px;cursor:pointer}.panel{margin-top:24px;padding:24px;border-radius:20px;background:white;box-shadow:0 10px 40px rgba(0,0,0,.08)}.muted{color:#667085}</style></head><body><main><p class="muted">codingVibes desktop</p><h1 id="view">Home</h1><p id="request">\${escapeForHtml(spec.request.slice(0,220))}</p><div class="nav"><button data-view="Home">Home</button><button data-view="Explore">Explore</button><button data-view="Settings">Settings</button></div><section class="panel"><h2 id="panelTitle">Get started</h2><p id="status">Local data and core interactions work without a hosted API.</p><button id="action">Save locally</button></section></main><script>const view=document.querySelector('#view'),title=document.querySelector('#panelTitle'),status=document.querySelector('#status');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view.textContent=b.dataset.view;title.textContent=b.dataset.view;status.textContent=b.dataset.view==='Explore'?'Your records and collections will appear here.':'Manage your product locally without a hosted API.'});document.querySelector('#action').onclick=()=>status.textContent='Saved locally.';</script></body></html>`},
    {path:'test/smoke.test.js',content:`import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';test('desktop shell is real HTML',()=>{const html=fs.readFileSync('src/index.html','utf8');assert.match(html,/data-view="Home"/);assert.match(html,/Save locally/);});\n`},
    {path:'README.md',content:commonReadme(spec,target)+'\nRun npm install and npm start on the target OS. Package with your preferred Electron distribution tooling. The generated UI is local-first and provider-neutral.\n'},
  ],summary:`Generate \${target.label}`,manifestHash:hash(spec),source:'deterministic'};if(target.id==='desktop-tauri')return {files:[
    {path:'package.json',content:json({name:'codingvibes-tauri',private:true,type:'module',scripts:{check:'node --check src/main.js',test:'node --test test/smoke.test.js'},dependencies:{'@tauri-apps/api':'^2.9.0'},devDependencies:{'@tauri-apps/cli':'^2.9.0'}})},
    {path:'src/main.js',content:`console.log('codingVibes Tauri frontend');\n`},
    {path:'src/index.html',content:`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>codingVibes</title></head><body><main><h1>codingVibes</h1><p>${escapeForHtml(spec.request.slice(0,220))}</p></main><script type="module" src="/main.js"></script></body></html>\n`},
    {path:'src-tauri/tauri.conf.json',content:json({'$schema':'https://schema.tauri.app/config/2',productName:'codingVibes',version:'0.1.0',identifier:'com.codingvibes.app',build:{frontendDist:'../src'},app:{windows:[{title:'codingVibes',width:1280,height:800,resizable:true}],security:{csp:"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:;"},bundle:{active:true,targets:'all'}}})},
    {path:'src-tauri/build.rs',content:`fn main(){tauri_build::build()}\n`},
    {path:'src-tauri/src/main.rs',content:`fn main(){tauri::Builder::default().run(tauri::generate_context!()).expect("error while running codingVibes");}\n`},
    {path:'src-tauri/Cargo.toml',content:`[package]\nname="codingvibes-app"\nversion="0.1.0"\nedition="2021"\n\n[build-dependencies]\ntauri-build={version="2"}\n\n[dependencies]\ntauri={version="2",features=[]}\n`},
    {path:'test/smoke.test.js',content:`import test from'node:test';import assert from'node:assert/strict';test('desktop source exists',()=>assert.ok(true));\n`},
    {path:'README.md',content:commonReadme(spec,target)+'\nRequires Rust/Cargo and Tauri tooling on the build machine. The generated frontend is bundled from src/index.html.\n'},
  ],summary:`Generate ${target.label}`,manifestHash:hash(spec),source:'deterministic'};
  if(target.id==='multiplatform-kmp')return {files:[
    {path:'settings.gradle.kts',content:`pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }\ndependencyResolutionManagement { repositories { google(); mavenCentral() } }\nrootProject.name="codingvibes-kmp"\ninclude(":shared")\n`},
    {path:'build.gradle.kts',content:`plugins { kotlin("multiplatform") version "2.2.10" apply false }\n`},
    {path:'shared/build.gradle.kts',content:`plugins { kotlin("multiplatform") }\nkotlin { jvm(); iosArm64(); iosSimulatorArm64(); js(IR) { browser() } }\n`},
    {path:'shared/src/commonMain/kotlin/App.kt',content:`package codingvibes\nobject AppInfo{const val title="codingVibes";const val request="${escapeForCode(spec.request.slice(0,160))}"}\n`},
    {path:'README.md',content:commonReadme(spec,target)+'\nUse the Gradle/KMP toolchain to add the exact platform targets and produce each artifact.\n'},
  ],summary:`Generate ${target.label}`,manifestHash:hash(spec),source:'deterministic'};
  // web-node and unknown target fall back to the existing generator upstream
  return null;
}

function escapeForCode(s){return String(s).replaceAll('\\','\\\\').replaceAll('`','\`').replaceAll('${','\\${').replaceAll("'","\\'").replaceAll('"','\\"');}
function escapeForHtml(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');}
