import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root=process.cwd();
const envPath=path.join(root,'.env.local');
const dataDirs=['data','data/projects','data/worktrees','data/checkpoints','data/media','data/backups'];

const secret=bytes=>crypto.randomBytes(bytes).toString('base64url');
if(!fs.existsSync(envPath)){
  const lines=[
    '# Build Vibe local environment — generated by npm run setup',
    'NODE_ENV=development',
    'HOST=127.0.0.1',
    'PORT=4400',
    'DATABASE_PATH=./data/codingvibes.db',
    'CODINGVIBES_DB_BACKEND=sqlite',
    'DATABASE_URL=',
    `CODINGVIBES_SESSION_SECRET=${secret(48)}`,
    `CODINGVIBES_CREDENTIALS_KEY=${secret(32)}`,
    `CODINGVIBES_ATTESTATION_SECRET=${secret(48)}`,
    'CODINGVIBES_PUBLIC_URL=http://127.0.0.1:4400',
    'CODINGVIBES_ALLOWED_ORIGINS=http://127.0.0.1:4400',
    'CODINGVIBES_TRUST_PROXY=false',
    'CODINGVIBES_RUNTIME=local',
    'CODINGVIBES_ALLOW_HOST_EXECUTION=false',
    'CODINGVIBES_ENABLE_BROWSER=true',
    'CODINGVIBES_CAPTURE_SCREENSHOTS=false',
    'CODINGVIBES_PROJECT_ROOT=./data/projects',
    'CODINGVIBES_WORK_ROOT=./data/worktrees',
    'CODINGVIBES_CHECKPOINT_ROOT=./data/checkpoints',
    'CODINGVIBES_MEDIA_ROOT=./data/media',
    'CODINGVIBES_BACKUP_ROOT=./data/backups',
    'CODINGVIBES_ENFORCE_QUOTAS=false',
    'CODINGVIBES_BILLING_REQUIRED=false',
    'CODINGVIBES_DEPENDENCY_NETWORK=',
    'CODINGVIBES_PROVIDER=openai',
    'CODINGVIBES_BASE_URL=https://api.openai.com/v1',
    'CODINGVIBES_MODEL_CHEAP=gpt-4o-mini',
    'CODINGVIBES_MODEL_STANDARD=gpt-4o-mini',
    'CODINGVIBES_MODEL_PREMIUM=gpt-4.1',
    'CODINGVIBES_PROVIDER_CHAIN=omniroute,openrouter,openai',
    'OPENAI_API_KEY=',
    'OPENROUTER_API_KEY=',
    'ANTHROPIC_API_KEY=',
    'DEEPSEEK_API_KEY=',
    'GROQ_API_KEY=',
    'STRIPE_SECRET_KEY=',
    'STRIPE_WEBHOOK_SECRET=',
    'STRIPE_PRICE_PRO_MONTHLY=',
    'STRIPE_PRICE_TEAM_MONTHLY=',
    'STRIPE_PRICE_BUSINESS_MONTHLY=',
    'PADDLE_API_KEY=',
    'PADDLE_WEBHOOK_SECRET=',
    'PADDLE_PRICE_PRO_MONTHLY=',
    'PADDLE_PRICE_TEAM_MONTHLY=',
    'PADDLE_PRICE_BUSINESS_MONTHLY=',
    'PADDLE_CHECKOUT_URL=http://127.0.0.1:4400/pay',
    'PADDLE_CLIENT_TOKEN=',
    'CODINGVIBES_BILLING_PROVIDER=stripe',
    'CODINGVIBES_MIROFISH_URL=',
    'CODINGVIBES_MIROFISH_API_KEY='
  ];
  fs.writeFileSync(envPath,lines.join('\n')+'\n','utf8');
  console.log('Created .env.local');
}else console.log('.env.local already exists; leaving it unchanged.');
for(const dir of dataDirs)fs.mkdirSync(path.join(root,dir),{recursive:true});
console.log('Created local data directories.');
console.log('Next: add a model API key, then run npm start. For PostgreSQL, copy .env.postgres.example to .env.postgres.local, run npm run db:postgres:up, then npm run db:postgres:setup.');
