import http from 'node:http';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {Store} from './db/store.js';
import {ModelRouter} from './ai/router.js';
import {executeBuild,verifyExistingRun} from './agent/orchestrator.js';
import {hashPassword,verifyPassword,signSession,verifySessionToken,setSessionCookie,clearSessionCookie,readSessionCookie} from './security/auth.js';
import {sendJson,sendText,readJson,streamSse} from './http/json.js';
import {resolveInside} from './core/safe-path.js';
import {inspectWorkspace,commitWorkspace,revertWorkspace} from './git/workspace.js';
import {ensureProjectRepository} from './projects-workspace.js';
import {listTargets} from './targets/registry.js';
import {normalizeTargetId} from './targets/detect.js';
import {CODINGVIBES_VERSION} from './version.js';
import {fleetStatus} from './runners/status.js';
import {createCheckpoint,restoreCheckpoint} from './git/checkpoints.js';
import {requireRunnerToken,normalizeRunner} from './runners/registry.js';
import {listIntegrationDefinitions,testIntegration} from './integrations/connectors.js';
import {importGitHubRepository} from './integrations/github.js';
import {buildDiagnostics} from './agent/diagnostics.js';
import {planCatalog,currentPeriodKey,canStartRun,getPlan} from './billing/plans.js';
import {createCheckoutSession,verifyStripeSignature} from './billing/stripe.js';
import {readiness} from './ops/readiness.js';

const root=path.dirname(fileURLToPath(import.meta.url));const publicDir=path.join(root,'..','public');
export const store=new Store();export const router=new ModelRouter();
const HOST=process.env.HOST||'127.0.0.1';const PORT=Number(process.env.PORT||4400);const MAX_BODY=Number(process.env.CODINGVIBES_MAX_BODY_BYTES||2*1024*1024);const activeBuilds=new Map();const buckets=new Map();
function rateLimit(req){const key=req.headers['x-forwarded-for']?.split(',')[0]?.trim()||req.socket.remoteAddress||'unknown';const now=Date.now();if(buckets.size>10000){for(const [k,v] of buckets){if(now-v.start>60000)buckets.delete(k);}}const b=buckets.get(key)||{start:now,count:0};if(now-b.start>60000){b.start=now;b.count=0}b.count++;buckets.set(key,b);return b.count<=180;}
function auth(req){const token=readSessionCookie(req);if(!token)return null;const id=verifySessionToken(token);return id?store.getAuthSession(id):null;}
function requireAuth(req,res){const a=auth(req);if(!a){sendJson(res,401,{ok:false,error:'authentication_required'});return null}return a;}
function pathParam(pathname,prefix){return decodeURIComponent(pathname.slice(prefix.length));}
function sameOrigin(req){const origin=req.headers.origin;if(!origin)return true;try{return new URL(origin).host===req.headers.host}catch{return false}}
async function serveStatic(req,res){let pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/')pathname='/index.html';let target;try{target=resolveInside(publicDir,pathname.slice(1));}catch{return false}if(!fs.existsSync(target)||!fs.statSync(target).isFile())return false;const type={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon','.webmanifest':'application/manifest+json'}[path.extname(target)]||'application/octet-stream';sendText(res,200,fs.readFileSync(target),type);return true;}
async function readRawBody(req,max=MAX_BODY){return await new Promise((resolve,reject)=>{let data='';let size=0;req.setEncoding('utf8');req.on('data',chunk=>{size+=Buffer.byteLength(chunk);if(size>max){reject(Object.assign(new Error('body_too_large'),{status:413}));req.destroy();return;}data+=chunk});req.on('end',()=>resolve(data));req.on('error',reject)});}
function listFiles(dir){const out=[];const walk=(current,rel='')=>{for(const name of fs.readdirSync(current)){if(name==='.git'||name==='node_modules'||name==='.codingvibes')continue;const full=path.join(current,name),next=path.join(rel,name),st=fs.lstatSync(full);if(st.isSymbolicLink())continue;if(st.isDirectory())walk(full,next);else out.push(next.replaceAll('\\','/'));if(out.length>=1000)return;}};walk(dir);return out;}

export function createAppServer(){return http.createServer(async(req,res)=>{
 try{
  res.setHeader('x-content-type-options','nosniff');res.setHeader('x-frame-options','SAMEORIGIN');res.setHeader('referrer-policy','same-origin');res.setHeader('cross-origin-resource-policy','same-origin');res.setHeader('cross-origin-opener-policy','same-origin');res.setHeader('permissions-policy','camera=(),microphone=(),geolocation=()');res.setHeader('content-security-policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-src http: https:; frame-ancestors 'self'; base-uri 'self'; form-action 'self'");
  if(!rateLimit(req))return sendJson(res,429,{ok:false,error:'rate_limit'});
  const u=new URL(req.url||'/',`http://${req.headers.host||HOST}`),method=req.method||'GET';
  if(method==='GET'&&u.pathname==='/health')return sendJson(res,200,{ok:true,service:'codingvibes',version:CODINGVIBES_VERSION,model:router.getStatus(),runtime:process.env.CODINGVIBES_RUNTIME||(process.env.NODE_ENV==='production'?'daytona':'local'),time:new Date().toISOString()});
  if(method==='GET'&&u.pathname==='/ready'){const r=readiness({router});return sendJson(res,r.ready?200:503,{ok:r.ready,...r});}
  if(['POST','PUT','PATCH','DELETE'].includes(method)&&!sameOrigin(req))return sendJson(res,403,{ok:false,error:'cross_origin_request_blocked'});
  if(method==='POST'&&u.pathname==='/api/auth/signup'){const b=await readJson(req,MAX_BODY);const email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8)return sendJson(res,400,{ok:false,error:'valid email and password (8+ characters) required'});if(store.getUserByEmail(email))return sendJson(res,409,{ok:false,error:'account_exists'});const user=store.createUser(email,await hashPassword(password));const session=store.createAuthSession(user.id);setSessionCookie(res,signSession(session.id));return sendJson(res,201,{ok:true,user});}
  if(method==='POST'&&u.pathname==='/api/auth/login'){const b=await readJson(req,MAX_BODY),user=store.getUserByEmail(String(b.email||''));if(!user||!(await verifyPassword(String(b.password||''),user.password_hash)))return sendJson(res,401,{ok:false,error:'invalid_credentials'});const session=store.createAuthSession(user.id);setSessionCookie(res,signSession(session.id));return sendJson(res,200,{ok:true,user:{id:user.id,email:user.email,created_at:user.created_at}});}
  if(method==='POST'&&u.pathname==='/api/auth/logout'){const token=readSessionCookie(req);const id=token&&verifySessionToken(token);if(id)store.deleteAuthSession(id);clearSessionCookie(res);return sendJson(res,200,{ok:true});}
  if(method==='GET'&&u.pathname==='/api/auth/me'){const a=auth(req);return sendJson(res,200,{ok:true,user:a?store.getUser(a.user_id):null});}
  // Runner control-plane endpoints use a dedicated service token, never end-user sessions.
  if(u.pathname==='/api/fleet/runners/register'&&method==='POST'){try{requireRunnerToken(req.headers['x-codingvibes-runner-token']||String(req.headers.authorization||'').replace(/^Bearer\s+/i,''));const b=normalizeRunner(await readJson(req,MAX_BODY));return sendJson(res,200,{ok:true,runner:store.upsertRunner(b)})}catch(e){return sendJson(res,e.status||400,{ok:false,error:e.message})}}
  if(/^\/api\/fleet\/runners\/[^/]+\/heartbeat$/.test(u.pathname)&&method==='POST'){try{requireRunnerToken(req.headers['x-codingvibes-runner-token']||String(req.headers.authorization||'').replace(/^Bearer\s+/i,''));const id=pathParam(u.pathname,'/api/fleet/runners/').replace(/\/heartbeat$/,'');const b=await readJson(req,MAX_BODY);const runner=store.heartbeatRunner(id,{status:b.status,metadata:b.metadata});if(!runner)return sendJson(res,404,{ok:false,error:'runner_not_found'});return sendJson(res,200,{ok:true,runner})}catch(e){return sendJson(res,e.status||400,{ok:false,error:e.message})}}
  if(method==='GET'&&u.pathname==='/api/fleet/runners'){try{requireRunnerToken(req.headers['x-codingvibes-runner-token']||String(req.headers.authorization||'').replace(/^Bearer\s+/i,''));return sendJson(res,200,{ok:true,runners:store.listRunners({staleMs:Number(process.env.CODINGVIBES_RUNNER_STALE_MS||120000)})})}catch(e){return sendJson(res,e.status||401,{ok:false,error:e.message})}}
  if(method==='POST'&&u.pathname==='/api/webhooks/stripe'){const raw=await readRawBody(req,5*1024*1024);if(!verifyStripeSignature(raw,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET))return sendJson(res,400,{ok:false,error:'stripe_signature_invalid'});let event;try{event=JSON.parse(raw)}catch{return sendJson(res,400,{ok:false,error:'invalid_json'})};const obj=event?.data?.object||{};const ref=obj.client_reference_id;let billing=ref?store.getBilling(ref):null;if(!billing&&obj.subscription)billing=store.getBillingBySubscription(obj.subscription);if(event.type==='checkout.session.completed'&&ref){store.updateBilling(ref,{plan:String(obj.metadata?.plan||'pro'),status:'active',stripe_customer_id:obj.customer||null,stripe_subscription_id:obj.subscription||null});}else if((event.type==='customer.subscription.deleted'||event.type==='customer.subscription.updated')&&billing){const active=['active','trialing'].includes(obj.status);store.updateBilling(billing.user_id,{plan:active?billing.plan:'free',status:obj.status||'unknown',stripe_customer_id:obj.customer||billing.stripe_customer_id,stripe_subscription_id:obj.id||billing.stripe_subscription_id,current_period_end:obj.current_period_end?new Date(obj.current_period_end*1000).toISOString():billing.current_period_end,cancel_at_period_end:Boolean(obj.cancel_at_period_end)});}return sendJson(res,200,{ok:true});}
  const a=requireAuth(req,res);if(!a)return;const userId=a.user_id;
  if(method==='GET'&&u.pathname==='/api/billing'){const billing=store.getBilling(userId),usage=store.monthlyUsage(userId,currentPeriodKey());const plan=getPlan(billing.plan);return sendJson(res,200,{ok:true,billing:{...billing,stripe_customer_id:undefined,stripe_subscription_id:undefined},plan,usage,plans:planCatalog()});}
  if(method==='POST'&&u.pathname==='/api/billing/checkout'){const b=await readJson(req,MAX_BODY),plan=getPlan(String(b.plan||'pro'));if(!plan.priceEnv)return sendJson(res,400,{ok:false,error:'plan_not_billable'});const priceId=process.env[plan.priceEnv];const base=`${req.headers['x-forwarded-proto']||'http'}://${req.headers.host}`;try{const checkout=await createCheckoutSession({apiKey:process.env.STRIPE_SECRET_KEY,priceId,customerEmail:store.getUser(userId)?.email,clientReferenceId:userId,plan:plan.id,successUrl:String(b.successUrl||`${base}/?billing=success`),cancelUrl:String(b.cancelUrl||`${base}/?billing=cancel`)});return sendJson(res,200,{ok:true,checkout});}catch(e){return sendJson(res,503,{ok:false,error:e.message});}}
  if(method==='GET'&&u.pathname==='/api/model/status')return sendJson(res,200,{ok:true,...router.getStatus()});
  if(method==='GET'&&u.pathname==='/api/connectors')return sendJson(res,200,{ok:true,connectors:router.listConnectors(),chain:router.getStatus().chain});
  if(method==='POST'&&u.pathname==='/api/connectors/test'){const b=await readJson(req,MAX_BODY);return sendJson(res,200,await router.testConnection(String(b.provider||'')));}
  if(method==='GET'&&u.pathname==='/api/integrations')return sendJson(res,200,{ok:true,integrations:listIntegrationDefinitions()});
  if(method==='POST'&&u.pathname==='/api/integrations/test'){const b=await readJson(req,MAX_BODY);return sendJson(res,200,await testIntegration(String(b.integration||'')));}
  if(method==='POST'&&u.pathname==='/api/integrations/github/import'){const b=await readJson(req,MAX_BODY);let project=null;try{project=store.createProject(userId,{name:String(b.projectName||`${String(b.owner||'')}/${String(b.repo||'')}`).slice(0,80)||'Imported GitHub project'});const imported=await importGitHubRepository({owner:b.owner,repo:b.repo,ref:b.ref,projectName:project.name});const saved=store.updateProjectRepo(project.id,imported.repoPath);return sendJson(res,201,{ok:true,project:{...saved,repo_path:undefined},source:{owner:imported.owner,repo:imported.repo,ref:imported.ref,branch:imported.branch}});}catch(e){if(project)store.deleteProject(project.id,userId);return sendJson(res,400,{ok:false,error:e.message});}}
  if(method==='GET'&&u.pathname==='/api/fleet')return sendJson(res,200,{ok:true,version:CODINGVIBES_VERSION,...fleetStatus(store)});
  if(method==='GET'&&u.pathname==='/api/targets')return sendJson(res,200,{ok:true,targets:listTargets()});
  if(method==='GET'&&u.pathname==='/api/projects')return sendJson(res,200,{ok:true,projects:store.listProjects(userId)});
  if(method==='POST'&&u.pathname==='/api/projects'){const b=await readJson(req,MAX_BODY),name=String(b.name||'').trim().slice(0,80);if(!name)return sendJson(res,400,{ok:false,error:'name_required'});const p=store.createProject(userId,{name});try{const repo=await ensureProjectRepository(p);const saved=store.updateProjectRepo(p.id,repo);return sendJson(res,201,{ok:true,project:{...saved,repo_path:undefined}})}catch(e){return sendJson(res,500,{ok:false,error:`project_repo_init_failed: ${e.message}`})}}
  if(method==='GET'&&u.pathname.startsWith('/api/projects/')&&u.pathname.endsWith('/sessions')){const pid=pathParam(u.pathname,'/api/projects/').replace(/\/sessions$/,'');if(!store.getProject(pid,userId))return sendJson(res,404,{ok:false,error:'project_not_found'});return sendJson(res,200,{ok:true,sessions:store.listSessions(pid,userId)})}
  if(method==='POST'&&/^\/api\/projects\/[^/]+\/sessions$/.test(u.pathname)){const pid=pathParam(u.pathname,'/api/projects/').replace(/\/sessions$/,'');const b=await readJson(req,MAX_BODY);try{return sendJson(res,201,{ok:true,session:store.createSession(userId,pid,String(b.title||'New build').slice(0,120))})}catch(e){return sendJson(res,404,{ok:false,error:e.message})}}
  if(method==='GET'&&u.pathname.startsWith('/api/sessions/')&&u.pathname.endsWith('/messages')){const sid=pathParam(u.pathname,'/api/sessions/').replace(/\/messages$/,'');return sendJson(res,200,{ok:true,messages:store.listMessages(sid,userId)})}
  if(method==='GET'&&u.pathname.startsWith('/api/sessions/')&&u.pathname.endsWith('/runs')){const sid=pathParam(u.pathname,'/api/sessions/').replace(/\/runs$/,'');return sendJson(res,200,{ok:true,runs:store.listRuns(sid,userId)})}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/inspect')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/inspect$/,'');const run=store.getRun(id,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,...await inspectWorkspace(run.workspace)})}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/tasks')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/tasks$/,'');if(!store.getRun(id,userId))return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,tasks:store.listTasks(id)})}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/repository-index')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/repository-index$/,'');if(!store.getRun(id,userId))return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,index:store.getRepositoryIndex(id)})}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/usage')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/usage$/,'');if(!store.getRun(id,userId))return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,usage:store.listUsage(id,userId),summary:store.usageSummary(id,userId)})}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/diagnostics')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/diagnostics$/,'');const run=store.getRun(id,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});const evidence=store.listEvidence(id),usage=store.usageSummary(id,userId),review=[...evidence].filter(x=>x.type==='review').at(-1)?.payload||null;let inspect=null;try{inspect=await inspectWorkspace(run.workspace);}catch{}return sendJson(res,200,{ok:true,diagnostics:buildDiagnostics({run,evidence,usage,review,inspect})});}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/goal')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/goal$/,'');if(!store.getRun(id,userId))return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,goal:store.getGoal(id)})}
  if(method==='PATCH'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/goal')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/goal$/,'');if(!store.getRun(id,userId))return sendJson(res,404,{ok:false,error:'not_found'});const b=await readJson(req,MAX_BODY);return sendJson(res,200,{ok:true,goal:store.updateGoal(id,b)})}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/dependencies')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/dependencies$/,'');if(!store.getRun(id,userId))return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,dependencies:store.listDependencyRequests(id,userId)});}
  if(method==='POST'&&u.pathname.startsWith('/api/dependency-requests/')&&u.pathname.endsWith('/approve')){const id=pathParam(u.pathname,'/api/dependency-requests/').replace(/\/approve$/,'');const b=await readJson(req,MAX_BODY);if(!b.confirmed)return sendJson(res,400,{ok:false,error:'explicit_confirmation_required'});try{const approved=store.approveDependencyRequest(id,userId);if(!approved)return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,dependencyRequest:approved});}catch(e){return sendJson(res,404,{ok:false,error:e.message});}}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/checkpoints')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/checkpoints$/,'');if(!store.getRun(id,userId))return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,checkpoints:store.listCheckpoints(id).map(x=>({...x,path:undefined}))})}
  if(method==='POST'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/checkpoints')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/checkpoints$/,'');const run=store.getRun(id,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});const b=await readJson(req,MAX_BODY);const cp=createCheckpoint(run.workspace,path.resolve(process.env.CODINGVIBES_CHECKPOINT_ROOT||path.join(process.cwd(),'data','checkpoints')),String(b.name||'manual'));const saved=store.createCheckpoint(id,cp.name,cp.path,{manual:true});return sendJson(res,201,{ok:true,checkpoint:{...saved,path:undefined}})}
  if(/^\/api\/runs\/[^/]+\/checkpoints\/[^/]+\/restore$/.test(u.pathname)&&method==='POST'){const parts=u.pathname.split('/'),runId=parts[3],checkpointId=parts[5];const run=store.getRun(runId,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});const cp=store.getCheckpoint(checkpointId);if(!cp||cp.run_id!==runId)return sendJson(res,404,{ok:false,error:'checkpoint_not_found'});const b=await readJson(req,MAX_BODY);if(!b.confirmed)return sendJson(res,400,{ok:false,error:'explicit_confirmation_required'});const restored=restoreCheckpoint(run.workspace,cp.path);store.updateRun(runId,userId,{status:'edited'});store.addEvidence(runId,'checkpoint_restore',{checkpointId,checkpoint:cp.name});return sendJson(res,restored.ok?200:409,{ok:restored.ok,checkpointId})}
  if(method==='POST'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/cancel')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/cancel$/,'');const run=store.getRun(id,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});if(!['running','planning','dependency_install','building','artifact_collection','device_smoke','verifying','repairing'].includes(run.status))return sendJson(res,409,{ok:false,error:'run_not_active'});const active=activeBuilds.get(userId);if(active?.runId===id)active.controller.abort();store.updateRun(id,userId,{status:'cancelled'});store.updateGoal(id,{status:'cancelled'});store.addEvidence(id,'cancel_requested',{at:new Date().toISOString(),interrupted:Boolean(active?.runId===id)});return sendJson(res,200,{ok:true,status:'cancelled',interrupted:Boolean(active?.runId===id)})}
  if(method==='POST'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/resume')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/resume$/,'');const run=store.getRun(id,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});if(activeBuilds.has(userId))return sendJson(res,409,{ok:false,error:'build_already_running'});const b=await readJson(req,MAX_BODY);const cps=store.listCheckpoints(id);const cp=b.checkpointId?store.getCheckpoint(b.checkpointId):cps.at(-1);if(!cp)return sendJson(res,409,{ok:false,error:'no_checkpoint'});if(b.restore!==false){if(!b.confirmed)return sendJson(res,400,{ok:false,error:'explicit_confirmation_required'});restoreCheckpoint(run.workspace,cp.path);}store.updateRun(id,userId,{status:'running'});store.addEvidence(id,'resumed',{checkpointId:cp.id});const result=await verifyExistingRun({run:{...run,status:'running'},userId,store,router,onEvent:e=>{}});return sendJson(res,result.passed?200:422,{ok:result.passed,status:result.passed?'verified':'failed',checkpointId:cp.id,result});}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/evidence')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/evidence$/,'');if(!store.getRun(id,userId))return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,evidence:store.listEvidence(id)})}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/events')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/events$/,'');if(!store.getRun(id,userId))return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,events:store.listEvents(id,userId)})}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/changesets')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/changesets$/,'');if(!store.getRun(id,userId))return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,changesets:store.listChangesets(id)})}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/files')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/files$/,'');const run=store.getRun(id,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,files:listFiles(run.workspace)})}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/artifacts')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/artifacts$/,'');if(!store.getRun(id,userId))return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,artifacts:store.listArtifacts(id).map(a=>({...a,stored_path:undefined}))})}
  if(method==='GET'&&/^\/api\/runs\/[^/]+\/artifacts\/[^/]+$/.test(u.pathname)){const parts=u.pathname.split('/');const runId=parts[3],artifactId=parts[5];if(!store.getRun(runId,userId))return sendJson(res,404,{ok:false,error:'not_found'});const artifact=store.getArtifact(artifactId);if(!artifact||artifact.run_id!==runId||!artifact.stored_path)return sendJson(res,404,{ok:false,error:'artifact_not_downloadable'});const root=path.resolve(process.env.CODINGVIBES_ARTIFACT_ROOT||path.join(process.cwd(),'data','artifacts'));const target=path.resolve(artifact.stored_path);if(!(target===root||target.startsWith(root+path.sep))||!fs.existsSync(target))return sendJson(res,404,{ok:false,error:'artifact_not_found'});const stat=fs.statSync(target);if(stat.size!==Number(artifact.size))return sendJson(res,409,{ok:false,error:'artifact_size_changed'});const sha=createHash('sha256').update(fs.readFileSync(target)).digest('hex');if(sha!==artifact.sha256)return sendJson(res,409,{ok:false,error:'artifact_checksum_changed'});res.writeHead(200,{'content-type':'application/octet-stream','content-length':String(stat.size),'content-disposition':`attachment; filename=\"${path.basename(target).replace(/[^a-zA-Z0-9._-]/g,'_')}\"`,'x-artifact-sha256':sha,'cache-control':'private, no-store'});fs.createReadStream(target).pipe(res);return; }
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')&&u.searchParams.has('file')){const id=pathParam(u.pathname,'/api/runs/');const run=store.getRun(id,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});const file=u.searchParams.get('file');const target=resolveInside(run.workspace,file);return sendJson(res,200,{ok:true,path:file,content:fs.readFileSync(target,'utf8')})}
  if(method==='GET'&&u.pathname.startsWith('/api/runs/')){const id=pathParam(u.pathname,'/api/runs/');const run=store.getRun(id,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});return sendJson(res,200,{ok:true,run,evidence:store.listEvidence(id),changesets:store.listChangesets(id),events:store.listEvents(id,userId)})}
  if(method==='POST'&&u.pathname==='/api/agent/stream'){
    const b=await readJson(req,MAX_BODY),request=String(b.request||'').trim();if(!request)return sendJson(res,400,{ok:false,error:'request_required'});if(request.length>20000)return sendJson(res,413,{ok:false,error:'request_too_large'});if(process.env.CODINGVIBES_ENFORCE_QUOTAS==='true'||(process.env.CODINGVIBES_ENFORCE_QUOTAS!=='false'&&process.env.NODE_ENV==='production')){const billing=store.getBilling(userId),usage=store.monthlyUsage(userId,currentPeriodKey()),quota=canStartRun({plan:billing.plan,runs:usage.runs,tokens:usage.tokens});if(!quota.ok)return sendJson(res,402,{ok:false,error:'usage_limit_reached',billing:{plan:billing.plan,usage,quota}});}const project=store.getProject(b.projectId,userId);if(!project)return sendJson(res,404,{ok:false,error:'project_not_found'});if(activeBuilds.has(userId))return sendJson(res,409,{ok:false,error:'build_already_running'});const session=b.sessionId?store.getSession(b.sessionId,userId):store.createSession(userId,project.id,String(b.title||'New build').slice(0,120));if(!session)return sendJson(res,404,{ok:false,error:'session_not_found'});const controller=new AbortController();activeBuilds.set(userId,{runId:null,controller});const baseEmit=streamSse(res);const emit=e=>{if(e?.type==='run_created'){const active=activeBuilds.get(userId);if(active)active.runId=e.runId;}baseEmit(e)};try{await executeBuild({request,userId,sessionId:session.id,project,store,router,onEvent:emit,commit:false,targetId:normalizeTargetId(b.target),signal:controller.signal});res.end();}catch(e){emit({type:'error',error:e.message});res.end();}finally{activeBuilds.delete(userId)}return;
  }
  if(method==='POST'&&u.pathname.startsWith('/api/changesets/')&&u.pathname.endsWith('/commit')){const id=pathParam(u.pathname,'/api/changesets/').replace(/\/commit$/,'');const cs=store.getChangeset(id);if(!cs)return sendJson(res,404,{ok:false,error:'not_found'});const run=store.getRun(cs.run_id,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});if(cs.status!=='verified')return sendJson(res,409,{ok:false,error:'changeset_must_be_verified'});const b=await readJson(req,MAX_BODY);if(!b.confirmed)return sendJson(res,400,{ok:false,error:'explicit_confirmation_required'});const c=await commitWorkspace(run.workspace,cs.summary||'codingVibes changeset');if(!c.ok)return sendJson(res,409,{ok:false,error:c.stderr});const sha=(c.stdout.match(/\[[^ ]+ ([0-9a-f]+)\]/)||[])[1]||null;store.updateChangeset(id,{status:'committed',commit_sha:sha});return sendJson(res,200,{ok:true,commitSha:sha,stdout:c.stdout})}
  if(method==='PUT'&&/^\/api\/runs\/[^/]+\/files$/.test(u.pathname)){const id=pathParam(u.pathname,'/api/runs/').replace(/\/files$/,'');const run=store.getRun(id,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});const b=await readJson(req,MAX_BODY);if(typeof b.path!=='string')return sendJson(res,400,{ok:false,error:'path_required'});const target=resolveInside(run.workspace,b.path,{forWrite:true});fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,String(b.content??''),'utf8');store.updateRun(id,userId,{status:'edited'});const existing=store.listChangesets(id).filter(x=>x.status!=='committed').at(-1);if(existing)store.updateChangeset(existing.id,{status:'needs_verification'});else store.createChangeset(id,{status:'needs_verification',summary:'User edits',operations:[{type:'write',path:b.path}]});store.addEvidence(id,'user_edit',{path:b.path});return sendJson(res,200,{ok:true,path:b.path})}
  if(method==='POST'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/verify')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/verify$/,'');const run=store.getRun(id,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});const result=await verifyExistingRun({run,userId,store,router,onEvent:e=>{}});return sendJson(res,result.passed?200:422,{ok:result.passed,result})}
  if(method==='POST'&&u.pathname.startsWith('/api/runs/')&&u.pathname.endsWith('/revert')){const id=pathParam(u.pathname,'/api/runs/').replace(/\/revert$/,'');const run=store.getRun(id,userId);if(!run)return sendJson(res,404,{ok:false,error:'not_found'});const b=await readJson(req,MAX_BODY);if(!b.confirmed)return sendJson(res,400,{ok:false,error:'explicit_confirmation_required'});const c=await revertWorkspace(run.workspace,b.ref||'HEAD');store.addEvidence(id,'git_revert',{ref:b.ref||'HEAD',ok:c.ok,stdout:c.stdout,stderr:c.stderr});return sendJson(res,c.ok?200:409,{ok:c.ok,stdout:c.stdout,stderr:c.stderr})}
  if(await serveStatic(req,res))return;return sendJson(res,404,{ok:false,error:'not_found'});
 }catch(e){return sendJson(res,e.status||500,{ok:false,error:e.message})}
});}

export const server=createAppServer();
if(process.argv[1]===fileURLToPath(import.meta.url)){server.listen(PORT,HOST,()=>console.log(`codingVibes listening on http://${HOST}:${PORT}`));const shutdown=()=>{try{store.close()}finally{server.close(()=>process.exit(0))}};process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);}
